### ISSUE TITLE
Error complining on kernel version 5.15.5-76051505

### ISSUE THREAD

**Issue by weeryan17** [DisplayLink/evdi#329] opened 2021-12-01 11:47 UTC
* OS: Pop!_OS 21.04 hirsute (x86-64)
  * Kernel: 5.15.5-76051505-generic
  * Xorg: 2:1.20.11-1ubuntu1.1
  * DE: Cinnamon 4.8.6

I just updated my kernel, and it seams to have broken evdi. As far as I can tell this is due to the latest kernel removing the `drm/irq.h` file. I tried compiling from source and got this message.
```
In file included from /home/weeryan17/git/evdi/module/evdi_platform_dev.c:30:
/home/weeryan17/git/evdi/module/evdi_drm_drv.h:23:10: fatal error: drm/drm_irq.h: No such file or directory
   23 | #include <drm/drm_irq.h>
      |          ^~~~~~~~~~~~~~~
```
I don't know if this is due to the kernel being broken, or if that file will just no longer exist.
I saw there was issue #6 and the solution to that was to install `libdrm-dev` however I allready have that installed, and up to date so I'm fairly sure it's not that.
![image](https://user-images.githubusercontent.com/10491247/144229082-006c4317-915f-422a-8c65-36046ff07514.png)

**Comment by displaylink-mlukaszek** [comment] 2021-12-01 11:50
This is a duplicate of #308

**Comment by wvdakker** [comment] 2021-12-01 11:51
See #322

**Closed by displaylink-mlukaszek** 2021-12-01 11:50 UTC

**Comment by weeryan17** [comment] 2021-12-01 11:52
Didn't see that, sorry!
