### ISSUE TITLE
Not detected 

### ISSUE THREAD

**Issue by plombix** [DisplayLink/evdi#113] opened 2018-01-16 15:19 UTC
I have a debian : 
`Linux debian 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux`

service is running : 
`● dlm.service - DisplayLink Manager Service
   Loaded: loaded (/lib/systemd/system/dlm.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-01-16 16:06:17 CET; 4min 46s ago
  Process: 655 ExecStartPre=/bin/sh -c modprobe evdi || (dkms install evdi/4.1.9 && modprobe evdi) (code=exited, status=0/SUCCESS)
 Main PID: 663 (DisplayLinkMana)
    Tasks: 32 (limit: 4915)
   CGroup: /system.slice/dlm.service
           └─663 /opt/displaylink/DisplayLinkManager
`

All instalation went **great** ( it was a sign,  i should know that now -_-) .

BUT (there it is)  the damm thing is not detected  : 

`
•100% ➜ xrandr --listproviders                                         
Providers: number : 0

~ 
•100% ➜ xrandr                
Screen 0: minimum 320 x 200, current 1366 x 768, maximum 8192 x 8192
XWAYLAND0 connected 1366x768+0+0 (normal left inverted right x axis y axis) 280mm x 160mm
   1366x768      59.98*+
`
Dmesg however  shows  it : 

`[ +10.414559] usb 4-2: new SuperSpeed USB device number 3 using xhci_hcd
[  +0.020743] usb 4-2: New USB device found, idVendor=17e9, idProduct=ff03
[  +0.000003] usb 4-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000002] usb 4-2: Product: MB168B
[  +0.000002] usb 4-2: Manufacturer: DisplayLink
[  +0.000001] usb 4-2: SerialNumber: G4LMTF160122
[  +6.620679] evdi: [D] evdi_painter_connect:572 (dev=1) Connected with ffffa09a2f231c00
[  +0.000002] evdi: [D] evdi_detect:75 (dev=1) Painter is connected
[  +0.000079] evdi: [D] evdi_painter_crtc_state_notify:481 (dev=1) Notifying crtc state: 3`

What am i missing & /  or  doing wrong   ?

**Comment by dawikur** [comment] 2018-01-16 17:47
Are you using xorg? Which version?
Try logout login with device connected.

**Comment by MonteShaffer** [comment] 2018-03-06 19:19
@plombix Any luck with Debian.  You can see my issue post here:  https://github.com/DisplayLink/evdi/issues/124  and a more updated post here: https://github.com/AdnanHodzic/displaylink-debian/issues/116

I am curious what your dmesg is reading ... I am getting a flooded error.

```sudo dmesg```

Also I have some weird info in the lsusb and curious what you are experiencing...

```sudo lsusb -v -d 17e9:```


"** UNRECOGNIZED:  1b 5f 01 00 19 05 00 01 03 00 04 04 01 00 03 d0 00 02 04 00 bd 1f 00 01 04 01 02"

**Comment by displaylink-dkurek** [comment] 2020-09-11 11:49
Nothing happened in this thread for quite some time. I will close it. If the issue is still visible please raise a new one with updated components and description. Thanks!

**Closed by displaylink-dkurek** 2020-09-11 11:49 UTC
