### ISSUE TITLE
Plasma 5.8 compositor issues

### ISSUE THREAD

**Issue by carbinefreak** [DisplayLink/evdi#46] opened 2016-10-07 18:13 UTC
Running Latest kernel 4.8 with latest KDE Plasma 5.8 there are some major issues with the compositor and libevdi. The issue is the compositor no longer does proper partial screen paints even without DisplaylinkManager running or displaylink device plugged in. the only way to "fix" this is to enable full screen refreshes but that causes major performance issues. The issue is only present when libevdi is loaded, if i boot without the module everything is normal.

```
spectre-gentoo carbinefreak # uname -r
4.8.0
spectre-gentoo carbinefreak # equery list evdi
 * Searching for evdi ...
[I-O] [  ] x11-drivers/evdi-1.2.64:0
spectre-gentoo carbinefreak # equery list x11-drivers/displaylink-driver
 * Searching for displaylink-driver in x11-drivers ...
[I-O] [  ] x11-drivers/displaylink-driver-1.2.58:0
spectre-gentoo carbinefreak # equery list plasma
 * Searching for plasma ...
[IP-] [  ] kde-frameworks/plasma-5.26.0:5/5.26
spectre-gentoo carbinefreak # equery list plasma-desktop
 * Searching for plasma-desktop ...
[I-O] [  ] kde-plasma/plasma-desktop-5.8.0:5
spectre-gentoo carbinefreak # 
```

**Comment by displaylink-mlukaszek** [comment] 2016-11-17 07:51
Would it be worth raising with KDE?

**Comment by moparisthebest** [comment] 2017-01-03 17:56
@carbinefreak I hit this same problem on arch linux, you said enabling full screen refreshes works around this bug, do you mind saying how you did that?

**Comment by bonanza123** [comment] 2017-01-25 19:43
@moparisthebest open `/usr/bin/kcmshell5 kwincompositing` > vsync > full repaints

**Comment by displaylink-mlukaszek** [comment] 2017-02-01 09:05
We have a fix for this that we'll be including in next Ubuntu release.

**Comment by moparisthebest** [comment] 2017-02-01 14:49
I must be running into a different bug then because enabling full repaints that way didn't fix my problem, thanks for the confirmation though!

**Comment by carbinefreak** [comment] 2017-03-03 19:15
Sadly with the new release it still tears on applications regardless of the renderer, but it is is getting better.

**Comment by displaylink-dkurek** [comment] 2018-07-18 06:17
Does someone see this problem with the latest releases?

**Comment by displaylink-dkurek** [comment] 2018-08-01 08:00
No response for some time. Hopefully, the issue is gone :)

**Closed by displaylink-dkurek** 2018-08-01 08:00 UTC
