### ISSUE TITLE
Cursor Glitches on Gnome 3.20 and KDE Plasma

### ISSUE THREAD

**Issue by aiudirog** [DisplayLink/evdi#29] opened 2016-06-26 19:18 UTC
Hi, I've been using evdi and the DisplayLink  driver with my StarTech 4K USB 3.0 to HDMI adapter and I am very happy with how it works, except that have noticed that around borders for windows and widgets that the cursor will flicker and trail or will simply disappear.  I did some testing as I have both Gnome and Plasma installed on Arch Linux and it happened in both. I also noticed that I was using an older version, so before commenting, I pulled down the current source and built it and installed it but the issue continued. If you would like a video, I can probably put one together.

Thank you

**Comment by unfulvio** [comment] 2016-06-26 23:18
this could be a power issue - for example my display came with a usb Y cable, if I connect only 1 end of the usb cable I have got (albeit very occasionally) similar glitches as those you describe, but if I use both plugs the problem never manifests

**Comment by aiudirog** [comment] 2016-06-27 00:41
That's interesting.  Mine did not come with a Y cable, but I have found the issue to be very predictable on what items on my screen it will glitch over, which led me to believe it was more software than hardware.  What's even more interesting is I tried to record a screen cast of it using https://extensions.gnome.org/extension/690/easyscreencast/ and the problem disappeared while I was recording and returned promptly when I stopped recording. I can video it with my phone though, just not using a screen recorder.

**Comment by JumpLink** [comment] 2016-06-28 07:55
I have a similar problem, see my [2 videos for demonstration](https://goo.gl/photos/LesUyBiDykJEMM1LA).

This issue occurs with me but do not force on the monitor plugged in with DisplayLink, but I have this issue **in combination with DisplayLink only** (or only with 4 Screens)

I use the [I-TEC USB 3.0 Display Video Adapter DVI](https://www.amazon.de/gp/product/B0083XYD0O/ref=oh_aui_detailpage_o07_s00?ie=UTF8&tag=boost15404-21) with the DisplayLink DL-3500 Chipset.

This seems to be a known bug, see [support.displaylink.com](http://support.displaylink.com/knowledgebase/articles/825819-mouse-cursor-flickers-on-the-primary-ubuntu-screen).
Is there a solution or useful tips?

**Comment by DarkSpyro003** [comment] 2016-06-28 09:08
Put your compositor into a full-screen repainting method (meaning redraw the entire screen every frame, not just changed areas). This will fix it, but be aware that displaylink CPU time and latency may increase greatly.

**Comment by displaylink-mlukaszek** [comment] 2016-06-28 11:22
We've seen this as well with KDE. This disappears if you change the compositor type to Xrender.

**Comment by DarkSpyro003** [comment] 2016-06-28 11:58
Xrender is comparatively slow for compositing as well. The issue also occurs when running without a compositor.

**Comment by JumpLink** [comment] 2016-06-29 07:38
My issue seems to be resolved since last linux kernel update to version
4.4.0-28.47, can anyone confirm this?

![auswahl_216](https://cloud.githubusercontent.com/assets/1073989/16444179/22d568ec-3ddd-11e6-9191-20eab53f80b8.png)

**Comment by DarkSpyro003** [comment] 2016-06-29 08:31
Still having the issue with kernel 4.4.0-28.47.

**Comment by aiudirog** [comment] 2016-06-30 01:12
I'm on kernal 4.6.2-1.


@DarkSpyro003 It seems like Gnome has dropped the option when they adopted Mutter to control compositing unfortunately.

**Comment by JumpLink** [comment] 2016-06-30 09:12
My issue is definitely fixed since last update, maybe from another updated package?

CPU: Intel® Core™ i7-4790K CPU @ 4.00GHz × 8
GPU: Intel® Haswell Desktop 
OS: Ubuntu 16.04 LTS 64-Bit
```
dpkg -l gnome-shell
gnome-shell 3.20.2-1ubuntu1~xenia amd64
```

I use the [GNOME3 Staging PPA](https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging).

**Comment by DarkSpyro003** [comment] 2016-06-30 10:11
@JumpLink the command doesn't seem to do anything.
Possibly the gnome compositor or compositor settings changed to do repaints differently in the staging version?
Is the issue resolved for you on other desktop environments as well?

**Comment by DarkSpyro003** [comment] 2016-06-30 10:14
Note that I'm seeing this issue in XFCE as well, not just KDE and Gnome.

**Comment by aiudirog** [comment] 2016-07-01 20:32
@JumpLink I am actually on the same Gnome version you updated to (albeit on Arch and not Ubuntu) and have been since it came out in May.  Is there any chance when it upgraded you were switched over to Wayland? I noticed that the option to choose "Gnome on Wayland" from the gdm lock screen disappeared this version and I am still using X11, but maybe you were forced to change?

I have done some work with graphics drivers and I noticed that the code here implements custom cursor functionality. Does anyone know if replacing it with the stock DRM functionality would break anything, just for testing purposes?

**Comment by aiudirog** [comment] 2016-07-02 00:11
Sorry for double posting, I tried editing my last comment a few times and got an undefined error.

I found that the preprocessor checks to change functions for kernel versions greater than 4.6 prevented me from compiling as `drm_connector_unregister_all()` doesn't exist yet in 4.6 and `drm_gem_object_lookup()` hasn't been updated to the new version. Not sure why this is the case, but I had to up the version checks to 4.7 to get it to compile. After that, I removed all of the cursor callbacks to see if that would affect anything (since they are optional anyways, as stated in drm_crtc.h). None of these changes did.  

Maybe the issue is actually in the user space DisplayLink service?

**Comment by displaylink-mlukaszek** [comment] 2016-08-17 13:22
@aiudirog fixes for 4.6 and 4.7 kernels are now pushed to devel branch. You could recompile the module and the library, the libevdi API has not changed so no change is required in DisplayLinkManager.

**Comment by aiudirog** [comment] 2016-08-17 16:24
@displaylink-mlukaszek The master branch compiles now that I am on kernel 4.7.0, but I will download the devel branch and see if anything else changes. As of right now, the cursor issue only seems to affect monitors that aren't over USB while the USB port is plugged. I have a built-in, HDMI, and  USB-HDMI display right now and I just tried every single combination of on-off of all of them and it only occurs when the USB-HDMI is plugged in with one or both of the other devices and only on those devices. 

Currently I am running the driver via the Arch Wiki instructions using `xrandr --setprovideroutputsource [# for modesetting, typically 1] [# for intel, typically 0]`. Is this the correct?

**Comment by displaylink-mlukaszek** [comment] 2016-08-18 15:13
A blinking cursor on multi-monitor setup is unfortunately a generic problem, and there are multiple reports of this in the web. E.g. [here](https://askubuntu.com/questions/450655/mouse-flickering-on-one-of-my-two-screens), [here](https://askubuntu.com/questions/623636/cursor-flickering-and-disappearing-with-dual-screen-setup) or [here](https://unix.stackexchange.com/questions/218269/mouse-pointer-blinks-and-sometimes-disappears).

The repaints not being correct with different compositors is interesting. I'd be keen to see what are the exact rectangles evdi is being told as requiring refresh - as essentially they will be propagated from kernel to userspace, and devices will update screens accordingly. Could someone check if equivalent screen corruptions appear on a multi-screen setup directly attached to built-in GPUs?

**Comment by mschaefer-es** [comment] 2016-08-18 15:26
I am experiencing this problem on my Dell Precision 5510 using the built-in Intel GPU (listed by lspci as HD Graphics P530). The discrete Nvidia GPU is disabled. The flickering does not occur when I attach a screen using HDMI, however I can only attach one screen this way.  Is there anything I can do to help? I would be willing to buy a thunderbolt adapter to test if the problem occurs there as well. Are there any dual-HDMI thunderbolt adapters out there?

**Comment by nekromoff** [comment] 2016-10-06 20:36
happening to me as well

4.7.0-040700-generic #201607241632 SMP Sun Jul 24 20:34:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Description:    Ubuntu 16.04.1 LTS
evdi                   40960  2
drm_kms_helper        147456  2 i915,evdi
drm                   364544  11 i915,evdi,drm_kms_helper
Bus 002 Device 013: ID 17e9:4307 DisplayLink

**Comment by carbinefreak** [comment] 2016-10-06 22:16
Same issue here with kernel 4.8 and KDE plasma 5.8 on latest evdi and binary.

**Comment by perk11** [comment] 2016-10-13 09:27
I'm also experiencing this on KDE Plasma 5.9.1. Setting `Tearing prevention ("vsync")` option to "Full screen repaints" fixes it.

**Comment by nekromoff** [comment] 2016-10-13 09:34
I can confirm that fixes it.
However slow cursor repaint still happens.

**Comment by displaylink-mlukaszek** [comment] 2017-02-17 08:16
Recent 1.3 release of Ubuntu driver for DisplayLink devices uses the freshest evdi and has fixes for corruptions in KDE - you should no longer require full screen repaints. Please test and report back - thanks.

**Comment by perk11** [comment] 2017-04-19 02:47
Unfortunately I can't check this because of having this more serious issue http://displaylink.org/forum/showthread.php?t=64952

**Comment by majgis** [comment] 2017-09-14 19:13
Ubuntu 17.04
Gnome 3.24
Intel® HD Graphics 630 (Kaby Lake GT2)
Dell Precision 5520

I added `/usr/share/X11/xorg.conf.d/20-intel.conf` as described in #85 which got DisplayLink device working but I was experiencing cursor glitches.

I removed `Option "TearFree" "true"` from `/usr/share/X11/xorg.conf.d/20-intel.conf` and no more cursor glitches!

**Comment by displaylink-dkurek** [comment] 2018-07-18 06:31
Does anyone still see this problem with the latest software? There has been quiet for some time so hopefully, we had got rid of those glitches :)

**Comment by majgis** [comment] 2018-07-20 22:08
I'm upgraded to Ubuntu 18.04.  I restored the 20-intel.conf file as I described above, but the trailing mouse pointer issue remains.

**Comment by LemonAndroid** [comment] 2018-08-04 17:45
I also have a flickering mouse cursor. i-tec dvi USB 3.0 display adapter.

**Comment by majgis** [comment] 2018-08-07 19:36
Success!
I removed `/usr/share/X11/xorg.conf.d/20-intel.conf` and added the following:

```
$ cat /usr/share/X11/xorg.conf.d/20-displaylink.conf
Section "Device"
  Identifier "DisplayLink"
  Driver "modesetting"
EndSection 
```

Reference:
https://support.displaylink.com/knowledgebase/articles/1181623-displaylink-ubuntu-driver-after-recent-x-upgrades

Also, it only worked with the `Option "PageFlip" "false"` line removed.

**Comment by Kostanos** [comment] 2018-08-11 23:29
I'm not sure if my issue is the same or I need to open another thread. I have also problems with mouse cursor right after I install DisplayLink drivers. Tried both latest versions 4.1 and 4.2, the same results.
Ubuntu 16.04, all latest updates.

I uploaded the video with behavior of cursor: https://youtu.be/vVwa-cVU_cA
Tried solution above, it doesn't change anything.

PS. screens itself works wheel.

**Comment by trxcllnt** [comment] 2019-03-11 23:13
@Kostanos in case you never found a fix, adding a new mode to `xrandr` as described here worked for me: https://wiki.archlinux.org/index.php/DisplayLink#Screen_redraw_is_broken.

I used the excellent [`displaylink-debian`](https://github.com/AdnanHodzic/displaylink-debian) installer to auto configure xorg for the displaylink devices, but was seeing the same cursor redraw issues as you connecting my System76 Bonobo WS to my [Acer XR382CQK](https://www.acer.com/ac/en/US/content/model/UM.TX2AA.002) displays. Hope this helps!

**Comment by Kostanos** [comment] 2019-03-12 13:15
Thank you @trxcllnt 
I'm in doubt which monitor resolution and refresh rate should I use with `gtf` command. As in my case I have two monitors connected. and both of them including the notebook's monitor itself has this issue.

**Comment by noraj** [comment] 2019-04-03 09:34
No matter the workaround I tired `/usr/share/X11/xorg.conf.d` I still get glitches with upstream and LTS kernel of Archlinux, the only workaround that worked was setting the Compositor to XRender instead of OpenGL.

**Comment by trxcllnt** [comment] 2019-04-03 11:03
@Kostanos ah yeah my monitors have a way of displaying the refresh rate as an overlay, so I used that to figure out the exact specs.

@bonanza123 I can't speak to the efficacy with Intel graphics, I've got NVidia cards in this laptop. I should also mention that while my steps _did_ get it working for a while, the monitors would go black about once per hour for a few seconds, and occasionally refuse to turn back on without a reboot. This was frustrating enough that I rearranged my desk and went back to using DisplayPort cables.

**Comment by Kostanos** [comment] 2019-04-03 15:04
@trxcllnt I think, I've used `displaylink-installer` up on your recommendation, and it works well.
fortunately I don't have any issue with monitores/adapter since I used it.
I also have added `/usr/share/X11/xorg.conf.d/20-displaylink.conf` file as per @majgis recommendation, but is has small difference, and, I think `displaylink-installer` added one more: `21-displaylink.conf` which has exactly the same content:
```
Section "Device"
  Identifier "DisplayLink"
  Driver "modesetting"
  Option "PageFlip" "false"
EndSection
```

My monitors works well since that.

My notebook is: [Lenovo Ideapad 720s](https://www.amazon.com/gp/product/B07FMH67WR/ref=as_li_tl?ie=UTF8&tag=kreativityboo-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B07FMH67WR&linkId=88a6f98b14d2a3b2d123aaa703bac9d4) with Nvidia GTX 1050i, has dual-boot Ubuntu 16.04 and Windows 10 - great notebook.
Yes, I found the issue on Windows when I playing Fortnite, I get some lags if I have display link connected (start to happen after some updates), so, for now, I disconnect it when I'm playing.

My displaylink adapter is [WavLink USB-C Dual 4K Ultra Dock DP Gen1](http://s.click.aliexpress.com/e/bOv2Kywk) - very good one, recommended.

@trxcllnt about the monitors going black, happened to me with one, I found that changing the HDMI cable to new one resolved the issue completely. It is hard to believe, but cable actually plays a big role on this.

**Comment by kowalcj0** [comment] 2019-04-16 13:15
@Kostanos I had exactly the same issue as you described earlier:
> I uploaded the video with behavior of cursor: https://youtu.be/vVwa-cVU_cA
> Tried solution above, it doesn't change anything.

your last solution worked like a charm!
Thank you for it!

My setup is:
* X1 Carbon 5th gen
* Fedora 29 (5.0.7-200.fc29.x86_64)
* [fedora-29-displaylink-1.6.0-2.x86_64.rpm
](https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v5.1.25-2/fedora-29-displaylink-1.6.0-2.x86_64.rpm)
* Gnome 3.30.2
* Targus Dual Video 4K Docking Station DOCK180
* Dell 27" monitor connected via Display Port

**Comment by AsiaHenzel** [comment] 2019-07-26 07:23
@Kostanos I also had a problem with the flickering mouse cursor and your solution worked for me!

My setup:

- Dell Inspiron 7559
- Ubuntu 18.04
- Kernel: 4.15.0-55-generic
- I have connected 2 external monitors using DisplayLink (Dell Docking Station D3100)

I found this solution mentioned here: https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1724307?comments=all.

**Comment by lhy0403** [comment] 2019-11-15 12:50
@Kostanos Thanks for your file, I have an Nvidia GTX960M and Displaylink (ASUS screen MB14AC)
After a tiny hack. My cursor glitches are fixed!
```
Section "Device"
    Identifier "DisplayLink"
    #Driver "modesetting" I commented out this line. See below
    Option "PageFlip" "false"
EndSection
```

-----------------------
Sorry, I cannot make sure my statements are 100% correct, but what I can confirm is my DisplayLink is currently working together with the proprietary Nvidia driver (https://github.com/DisplayLink/evdi/issues/2)

I have a GTX960M GPU which does not support directly render to the primary screen (maybe?)
This is my `xrander --blabla` output
```
╰─➤  xrandr --listmonitors
Monitors: 2
0: +*eDP-1-1 1920/344x1080/194+0+0  eDP-1-1
1: +DVI-I-2-1 1920/344x1080/194+1920+0  DVI-I-2-1

╰─➤  xrandr --listproviders
Providers: number : 3
Provider 0: id: 0x269 cap: 0x1, Source Output crtcs: 0 outputs: 0 associated providers: 2 name:NVIDIA-0
Provider 1: id: 0xc8 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x44 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 2 associated providers: 1 name:modesetting
```
**NOTE:**
**Provider0: Nvidia**
**Provider1: Displaylink**
**Provider2: Intel** (Maybe?)

I have a line in `/usr/share/sddm/scripts/Xsetup` which seems allowing GPU to render directly and put it to the screen.
```
╰─➤  cat /usr/share/sddm/scripts/Xsetup
#!/bin/sh
xrandr --setprovideroutputsource modesetting NVIDIA-0; xrandr --auto
```

OS: Arch Linux
```
uname -a : Linux MYLAPTOPNAME 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux
plasmashell 5.17.3

```

It makes the DisplayLink compatible with the Nvidia proprietary driver?

**Comment by stheid** [comment] 2020-02-21 08:02
## Issue still persists

Device: Dell Dockingstation D6000

gnome: 3.34.3
compositor: x11

kernel: 5.4.18
evdi: 1.6.4
GPU: Intel UHD 630

---
```
$> cat /usr/share/X11/xorg.conf.d/20-evdidevice.conf 
Section "Device"
	Identifier "Intel Graphics"
	Driver "intel"
EndSection
```

**Comment by mauromol** [comment] 2020-03-08 21:36
Just installed DisplayLink driver 5.2 on Linux Mint KDE 18.3 (based on Ubuntu 16.04). Seeing ghost tracks on the mouse pointer. Workarounds found, already mentioned: set vsync to "full screen repaints", or use XRender rendering engine instead of OpenGL 2.x/3.x. Using an i-Tec USB 3.0 docking station.

**Comment by 0k00l** [comment] 2020-03-27 17:15
In KDE Plasma disabling **Tering preventions("vsync")** fixed issue for me. I've setted its value to **Never** 

Settings --> Display and Monitor --> Compositor

**Comment by BarbecueSilver** [comment] 2020-04-21 09:25
@0k00l 
This made it run a lot faster too! :)

**Comment by mauromol** [comment] 2020-04-21 09:55
In my case, setting vsync to never does not solve the problem at all... The only setting that works in my case is "full screen repaints" with KDE.
Any words from DisplayLink? Back in 2017 they said that "Recent 1.3 release of Ubuntu driver for DisplayLink devices uses the freshest evdi and has fixes for corruptions in KDE - you should no longer require full screen repaints.", however I'm using 5.2 driver and still has that exact same problem under Linux Mint 18.3 (based on Ubuntu 16.04).

**Comment by 0k00l** [comment] 2020-04-21 11:18
> 
> 
> In my case, setting vsync to never does not solve the problem at all... The only setting that works in my case is "full screen repaints" with KDE.
> Any words from DisplayLink? Back in 2017 they said that "Recent 1.3 release of Ubuntu driver for DisplayLink devices uses the freshest evdi and has fixes for corruptions in KDE - you should no longer require full screen repaints.", however I'm using 5.2 driver and still has that exact same problem under Linux Mint 18.3 (based on Ubuntu 16.04).

I have intel GPU what you have ?

**Comment by mauromol** [comment] 2020-04-21 12:06
> I have intel GPU what you have ?

Me too. Haswell i5-4200M, no external graphics card.

**Comment by Adrian-Benavente** [comment] 2020-08-10 21:43
In KDE Plasma I solved it by setting the "Tearing Prevention <<vsync>>" option to "Never"

**Comment by thopiekar** [comment] 2020-09-09 17:50
Also works without any modifications.
Just make sure load evdi early from initramfs and set initial devices to 4 as recommended in DisplayLink's post.
Also make sure you add a xorg.conf with FlipPage false, etc.

Works nicely :)

**Comment by Adrian-Benavente** [comment] 2020-10-03 16:19
@thopiekar I have no idea how to do that neither I know what post are you talking about, can you explain me?

**Comment by displaylink-emajewsk** [comment] 2021-08-05 07:42
Closing this old bug. There have been many improvements in X11 over the years. We'll verify it on our end. Please create a new issue if the problem resurfaces. Thanks!

**Closed by displaylink-emajewsk** 2021-08-05 07:42 UTC
Labels: bug
