### ISSUE TITLE
Signal 6  with X plus kernel dump.

### ISSUE THREAD

**Issue by ghost** [DisplayLink/evdi#130] opened 2018-05-18 08:11 UTC
I'm having a problem with the evdi driver on Linux kernel `4.16.8`.

Whenever I try to `xrandr --setprovideroutputsource "$source" 1`, my Xserver crashes with the logs attached in the ptpb pastebin.

To restart the Xserver, I tried to make sure that the evdi module is unloaded with unplugging my device and calling `rmmod evdi`, and that was when I got the other greeting in my `dmesg`, which is attached at the top of the pastebin that was linked.

https://ptpb.pw/nG2A

**Comment by displaylink-dkurek** [comment] 2020-09-11 11:50
Nothing happened in this thread for quite some time. I will close it. If the issue is still visible please raise a new one with updated components and description. Thanks!

**Closed by displaylink-dkurek** 2020-09-11 11:50 UTC
