### ISSUE TITLE
Monitor no detect (always disconnected)

### ISSUE THREAD

**Issue by c0ki** [DisplayLink/evdi#105] opened 2017-09-19 15:00 UTC
Hello,

I have install ubuntu drivers from http://www.displaylink.com/downloads/ubuntu (v1.3.54).
When I start service (sudo systemctl start dlm.service), evdi not detect my monitor, it is always "disconnected" on xrandr `DVI-I-2-1 disconnected (normal left inverted right x axis y axis)`

On dmesg, i have this lines :
[  119.519601] evdi: loading out-of-tree module taints kernel.
[  119.519670] evdi: module verification failed: signature and/or required key missing - tainting kernel
[  119.521468] evdi: [I] Initialising logging on level 5
[  120.495274] nouveau 0000:01:00.0: DRM: resuming kernel object tree...
[  120.538220] nouveau 0000:01:00.0: priv: HUB0: 084014 ffffffff (1b70820d)
[  120.578537] nouveau 0000:01:00.0: priv: HUB0: 10ecc0 ffffffff (1d70822c)
[  120.656016] nouveau 0000:01:00.0: DRM: resuming client object trees...
[  120.665981] evdi: [D] add_store:195 Increasing device count to 1
[  120.666398] evdi: [D] evdi_crtc_init:312 drm_crtc_init: 0
[  120.666594] evdi: [W] evdi_painter_crtc_state_notify:363 Painter does not exist!
[  120.666596] evdi: [D] evdi_detect:78 Painter is disconnected
[  120.666598] [drm] Cannot find any crtc or sizes - going 1024x768
[  120.667501] evdi evdi.0: fb1: evdidrmfb frame buffer device
[  120.667502] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[  120.667502] [drm] No driver support for vblank timestamp query.
[  120.667503] [drm] evdi: evdi_stats_init
[  120.667510] [drm] Initialized evdi 1.3.43 20170117 on minor 2
[  120.845505] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff9df41dce6600 tries to close us
[  120.845506] evdi: [W] evdi_painter_disconnect:463  - ignoring
[  120.845779] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff9df41dce6600 tries to close us
[  120.845780] evdi: [W] evdi_painter_disconnect:463  - ignoring
[  120.919284] evdi: [D] evdi_detect:78 Painter is disconnected
[  120.919312] evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
[  120.919319] evdi: [D] evdi_detect:78 Painter is disconnected
[  120.919621] evdi: [D] evdi_painter_crtc_state_notify:360 (dev=0) Notifying crtc state: 3
[  120.919622] evdi: [W] evdi_painter_send_crtc_state:266 Painter is not connected!
[  120.922068] evdi: [D] evdi_painter_crtc_state_notify:360 (dev=0) Notifying crtc state: 3
[  120.922069] evdi: [W] evdi_painter_send_crtc_state:266 Painter is not connected!
[  120.931456] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff9df3fb729800 tries to close us
[  120.931456] evdi: [W] evdi_painter_disconnect:463  - ignoring
[  120.941050] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff9df3fb729800 tries to close us
[  120.941050] evdi: [W] evdi_painter_disconnect:463  - ignoring
[  120.944241] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff9df3fb729800 tries to close us
[  120.944242] evdi: [W] evdi_painter_disconnect:463  - ignoring
[  121.676159] evdi: [D] evdi_detect:78 Painter is disconnected
[  126.842902] nouveau 0000:01:00.0: DRM: evicting buffers...
[  126.842904] nouveau 0000:01:00.0: DRM: waiting for kernel channels to go idle...
[  126.842925] nouveau 0000:01:00.0: DRM: suspending client object trees...
[  126.844784] nouveau 0000:01:00.0: DRM: suspending kernel object tree...
[  128.099043] nouveau 0000:01:00.0: DRM: resuming kernel object tree...
[  128.141973] nouveau 0000:01:00.0: priv: HUB0: 084014 ffffffff (1b70820d)
[  128.182950] nouveau 0000:01:00.0: priv: HUB0: 10ecc0 ffffffff (1d70822c)
[  128.263781] nouveau 0000:01:00.0: DRM: resuming client object trees...
[  128.269500] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff9df3f9bf5800 tries to close us
[  128.269501] evdi: [W] evdi_painter_disconnect:463  - ignoring
[  128.274404] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connection to ffff9df3f9a05200 tries to close us
[  128.274404] evdi: [W] evdi_painter_disconnect:463  - ignoring
[  129.796414] evdi: [D] evdi_detect:78 Painter is disconnected

Have you got idea to evdi detect my monitor ?

Thank you

I use lubuntu 17.04 ;-)

**Comment by blackhold** [comment] 2017-09-19 21:33
Hi, I have debian 9.1 with kernel 4.9.0-3-amd64 and displaylink v.1.3.54. firmware-linux-nonfree installed. I have almost everything working, but:
- USB-Hub: yes
- Audio: yes (I have to check manually wich output to use)
- Ethernet: yes (it created interface LAN, not tested, assumed working)
- Power: yes (without displaylink)
- VGA: no (system seems not able to load driver and don't shows screen as connected)
- Minidisplayport: not tested

Kernel says:
Sep 19 17:15:24 melatonina kernel: [    2.643091] i915 0000:00:02.0: firmware: failed to load i915/skl_dmc_ver1_26.bin (-2)
Sep 19 17:15:24 melatonina kernel: [    2.643098] i915 0000:00:02.0: Direct firmware load for i915/skl_dmc_ver1_26.bin failed with error -2
Sep 19 17:15:24 melatonina kernel: [    2.643100] i915 0000:00:02.0: Failed to load DMC firmware [https://01.org/linuxgraphics/intel-linux-graphics-firmwares], disabling runtime power management.
Sep 19 17:15:24 melatonina kernel: [    2.643333] vgaarb: device changed decodes: PCI:0000:00:02.0,olddecodes=io+mem,decodes=io+mem:owns=mem

**Comment by displaylink-dkurek** [comment] 2020-09-11 11:48
Nothing happened in this thread for quite some time. I will close it. If the issue is still visible please raise a new one with updated components and description. Thanks!

**Closed by displaylink-dkurek** 2020-09-11 11:48 UTC
