### ISSUE TITLE
evdi_mode_valid: Mode rejected

### ISSUE THREAD

**Issue by Nubosch** [DisplayLink/evdi#77] opened 2017-01-31 17:02 UTC
evdi bb39d08 with DisplayManager 1.2.65 stopped working on my system. Am I doing something wrong?

:~# dmesg
[36786.708717] evdi: [D] evdi_detect:75 (dev=2) Painter is connected
[36786.708725] evdi: [D] evdi_painter_get_edid_copy:192 (dev=2) 00 ff ff
[36786.709077] evdi: [W] evdi_mode_valid:61 Mode 3840x2160@60 rejected
...
[36786.709168] evdi: [W] evdi_mode_valid:61 Mode 848x480@60 rejected

:~# uname -a
Linux nb-lx-hgc-001 4.9.0-1-amd64 #1 SMP Debian 4.9.2-2 (2017-01-12) x86_64 GNU/Linux

:~# hexdump -v -e '/1 "%02X "' /sys/devices/platform/evdi.0/drm/card2/card2-DVI-I-1/edid
00 FF FF FF FF FF FF 00 10 AC BE A0 4C 57 36 30 2D 19 01 04 A5 35 1E 78 3A E2 45 A8 55 4D A3 26 0B 50 54 A5 4B 00 71 4F 81 80 A9 C0 A9 40 D1 C0 E1 00 D1 00 01 01 4D D0 00 A0 F0 70 3E 80 3E 30 35 00 0F 28 21 00 00 1A 00 00 00 FF 00 47 43 4B 52 43 35 42 36 30 36 57 4C 0A 00 00 00 FC 00 44 45 4C 4C 20 50 32 34 31 35 51 0A 20 00 00 00 FD 00 1D 4C 1E 8C 36 00 0A 20 20 20 20 20 20 01 BF 02 03 1D F1 50 10 1F 20 05 14 04 13 12 11 03 02 16 15 07 06 01 23 09 1F 07 83 01 00 00 56 5E 00 A0 A0 A0 29 50 30 20 35 00 0F 28 21 00 00 1A 02 3A 80 18 71 38 2D 40 58 2C 25 00 0F 28 21 00 00 1E 01 1D 00 72 51 D0 1E 20 6E 28 55 00 0F 28 21 00 00 1E A3 66 00 A0 F0 70 1F 80 30 20 35 00 0F 28 21 00 00 1A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 EB

:~# xrandr --listproviders 
Providers: number : 4
Provider 0: id: 0xb8 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 2 associated providers: 2 name:modesetting
Provider 1: id: 0x93 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x71 cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 3: id: 0x4f cap: 0xd, Source Output, Source Offload, Sink Offload crtcs: 0 outputs: 0 associated providers: 0 name:HAINAN @ pci:0000:01:00.0

:~# xrandr --output DVI-I-2-1 --mode 1920x1080 --right-of eDP-1
xrandr: Output DVI-I-2-1 is not disconnected but has no modes
xrandr: cannot find mode 1920x1080

**Comment by markcia** [comment] 2017-01-31 19:42
Very similar issue with displaylink 1.3.43-1 on fedora 24 with kernel 4.9.6-100. I had used the fedora 24 RPM but it otherwise compiles by DKMS fine.

**Comment by displaylink-mlukaszek** [comment] 2017-02-01 09:06
This is a duplicate of #74. Releases from devel should not be used with DisplayLink Ubuntu driver (or, can only be used at your own risk that there might be API changes which require DLM to catch up).

**Closed by displaylink-mlukaszek** 2017-02-01 09:06 UTC

**Comment by Nubosch** [comment] 2017-02-02 09:30
thanks for the info, I was just trying to move forward cause of
https://github.com/DisplayLink/evdi/issues/68
and
https://github.com/AdnanHodzic/displaylink-debian/issues/47
so I'll stay around with my mouse cursor on black screen :)

**Comment by ment0s** [comment] 2017-02-16 17:08
As a quick suggestion. Copying libevdi.so from official driver for Ubuntu from DisplayLink site onto devel branch from github fixes the issue ( it might cause other as that but I havent noticed any ). Also I had to fully reboot for it to apply.
