### ISSUE TITLE
Provider detected but not the monitor

### ISSUE THREAD

**Issue by edjin** [DisplayLink/evdi#136] opened 2018-07-30 10:30 UTC
Hi !
I have installed the DisplayLink driver for use an MB169B+ monitor. It looks work but the monitor is not detecte by xrand. I am actualy use debian buster.

```bash
$ uname -a
Linux xxx 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux

$ systemctl status dlm.service
● dlm.service - DisplayLink Manager Service
   Loaded: loaded (/lib/systemd/system/dlm.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2018-07-29 12:07:44 CEST; 24h ago
  Process: 3986 ExecStartPre=/bin/sh -c modprobe evdi || (dkms install evdi/4.2.29 && modprobe evdi) (code=exited, status=0/SUCCESS)
 Main PID: 3988 (DisplayLinkMana)
    Tasks: 31 (limit: 4915)
   Memory: 18.0M
   CGroup: /system.slice/dlm.service
           └─3988 /opt/displaylink/DisplayLinkManager

$ xrandr --listproviders 
Providers: number : 2
Provider 0: id: 0x47 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 5 associated providers: 0 name:modesetting
Provider 1: id: 0x1c3 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 1 outputs: 1 associated providers: 0 name:modesetting

$ xrandr --listmonitors 
Monitors: 1
 0: +*eDP-1 1920/276x1080/155+0+0  eDP-1
```

and in my `syslog` file
```
Jul 30 12:15:09 xxx kernel: [ 4707.271888] usb 2-6: usbfs: process 3994 (DeviceManager_0) did not claim interface 1 before use
Jul 30 12:15:10 xxx kernel: [ 4708.237769] usb 2-6: USB disconnect, device number 6
Jul 30 12:15:11 xxx kernel: [ 4708.721763] usb 2-6: new SuperSpeed USB device number 7 using xhci_hcd
Jul 30 12:15:11 xxx kernel: [ 4708.746402] usb 2-6: New USB device found, idVendor=17e9, idProduct=ff0b, bcdDevice=31.13
Jul 30 12:15:11 xxx kernel: [ 4708.746404] usb 2-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jul 30 12:15:11 xxx kernel: [ 4708.746405] usb 2-6: Product: ASUSTEK MB169B+   
Jul 30 12:15:11 xxx kernel: [ 4708.746407] usb 2-6: Manufacturer: DisplayLink  
Jul 30 12:15:11 xxx kernel: [ 4708.746408] usb 2-6: SerialNumber: G7LMTF046968 
Jul 30 12:15:11 xxx mtp-probe: checking bus 2, device 7: "/sys/devices/pci0000:00/0000:00:14.0/usb2/2-6"
Jul 30 12:15:11 xxx mtp-probe: bus: 2, device: 7 was not an MTP device         
Jul 30 12:15:19 xxx kernel: [ 4717.345029] evdi: [D] evdi_painter_connect:573 (dev=1) Connected with 0000000034d1e2c2
Jul 30 12:15:19 xxx kernel: [ 4717.345037] evdi: [D] evdi_detect:75 (dev=1) Painter is connected
Jul 30 12:15:19 xxx kernel: [ 4717.345115] evdi: [D] evdi_painter_crtc_state_notify:482 (dev=1) Notifying crtc state: 3
Jul 30 12:15:19 xxx kernel: [ 4717.350658] evdi: [D] evdi_detect:75 (dev=1) Painter is connected
Jul 30 12:15:19 xxx kernel: [ 4717.350668] evdi: [D] evdi_painter_get_edid_copy:216 (dev=1) 00 ff ff 
Jul 30 12:15:19 xxx kernel: [ 4717.351111] evdi: [D] evdi_detect:75 (dev=1) Painter is connected
Jul 30 12:15:19 xxx kernel: [ 4717.351118] evdi: [D] evdi_painter_get_edid_copy:216 (dev=1) 00 ff ff 
Jul 30 12:15:19 xxx org.kde.KScreen[1136]: kscreen.xcb.helper: RRScreenChangeNotify
Jul 30 12:15:19 xxx org.kde.KScreen[1136]: kscreen.xcb.helper: #011Window: 35651588
Jul 30 12:15:19 xxx org.kde.KScreen[1136]: kscreen.xcb.helper: #011Root: 402   
Jul 30 12:15:19 xxx org.kde.KScreen[1136]: kscreen.xcb.helper: #011Rotation:  "Rotate_0"
Jul 30 12:15:19 xxx org.kde.KScreen[1136]: kscreen.xcb.helper: #011Size ID: 0  
Jul 30 12:15:19 xxx org.kde.KScreen[1136]: kscreen.xcb.helper: #011Size:  1920 1080
Jul 30 12:15:19 xxx org.kde.KScreen[1136]: kscreen.xcb.helper: #011SizeMM:  508 285
Jul 30 12:15:20 xxx org.kde.KScreen[1136]: kscreen.xrandr: Emitting configChanged()                                                                                                                                                                
```
Thinks for your help.

**Comment by displaylink-mlukaszek** [comment] 2018-07-30 11:24
Try running `xrandr --setprovideroutputsource 1 0`

**Comment by displaylink-dkurek** [comment] 2020-09-11 11:51
Nothing happened in this thread for quite some time. I will close it. If the issue is still visible please raise a new one with updated components and description. Thanks!

**Closed by displaylink-dkurek** 2020-09-11 11:51 UTC
