### ISSUE TITLE
Displaylink and evdi working after fresh installation, after reboot, fails to add providers to xrandr

### ISSUE THREAD

**Issue by jo3baltes** [DisplayLink/evdi#243] opened 2020-12-14 19:41 UTC
Initially please make sure the problem hasn't been already addressed:
  * [ x ] Are you using the latest driver?
    (https://www.displaylink.com/downloads/ubuntu)
  * [ n ] Are you using the latest EVDI version?
    (https://github.com/DisplayLink/evdi/releases) evdi 1.7.0-2 [AUR]
  * [ x ] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [ ? ] Is this issue related to evdi/kernel?
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

Arch 5.9.14 kernel
Xorg 1.20.10-2
Displaylink 5.3.1.34-4 [AUR]
Evdi 1.7.0-2

I can build and install displaylink on my Arch 5.9.14 kernel, and immediately after installing displaylink, I can see all of my xrandr providers, activate the displays and have no issues. 

After a reboot, the providers are gone and cannot be added back. My only way to resolve this is to repeat the displaylink build and install process:
 - yay displaylink

NOTE: /sys/devices/evdi/version is showing 1.8.0

`* displaylink.service - DisplayLink Manager Service
     Loaded: loaded (/usr/lib/systemd/system/displaylink.service; disabled; vendor preset: disabled)
     Active: active (running) since Mon 2020-12-14 14:16:01 EST; 26min ago
    Process: 11860 ExecStartPre=/sbin/modprobe evdi (code=exited, status=0/SUCCESS)
   Main PID: 11861 (DisplayLinkMana)
      Tasks: 51 (limit: 9125)
     Memory: 72.3M
     CGroup: /system.slice/displaylink.service
             `-11861 /usr/lib/displaylink/DisplayLinkManager

Dec 14 14:16:01 bolverkr systemd[1]: Starting DisplayLink Manager Service...
Dec 14 14:16:01 bolverkr systemd[1]: Started DisplayLink Manager Service.
`

No errors from systemd for displaylink, evdi, udl and dkms all appear to be loaded and working after the reboot, but no display providers are found / listed.

**Comment by displaylink-dkurek** [comment] 2020-12-15 19:07
I guess you shouldn't be using version 1.8.0 as it's incompatible with the last DisplayLink Manager release.
For kernel 5.9 and 5.10 there were created two releases: 1.7.1 and 1.7.2 (this one supports both 5.9 and 5.10).
Might be worth checking those :)

**Comment by abucodonosor** [comment] 2020-12-15 21:57
That is dupe of https://github.com/DisplayLink/evdi/issues/236

**Comment by displaylink-dkurek** [comment] 2020-12-16 08:01
Created #245 to gather those, with a bit more [hopefully] useful title.
Closing this one

**Closed by displaylink-dkurek** 2020-12-16 08:01 UTC
