### ISSUE TITLE
Ubuntu Kernel  5.11.0-40 issues.

### ISSUE THREAD

**Issue by pjones1063** [DisplayLink/evdi#320] opened 2021-11-20 01:06 UTC
It wont run at all on Ubuntu 20.04 with 5.11.0-40.  Below is error in the kernel ring buffer - dmesg when 5.11.0-40 is up:

<p>[ 30.391112] module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 000000004e8c48c2, val ffffffffc14c3d80

 

<br class="Apple-interchange-newline">

**Comment by astromatt42** [comment] 2021-12-27 01:40
This problem extends to Kernel 5.13.0-22. Same message multiple times in dmesg.
I have tried the new 5.5 Beta release, however no joy...

**Comment by FabianoLothor** [comment] 2022-04-28 04:03
+1

any workaround?

**Comment by catellie** [comment] 2022-05-28 20:36
Just tried this on Ubuntu 22.04 running 5.15.0-33 and the problem remains
(I had intentionally delayed upgrading since DisplayLink would not support non-LTS releases, but I guess I was over optimistic...)

**Comment by catellie** [comment] 2022-06-05 19:43
BTW: Also 5.15.0-35

**Comment by catellie** [comment] 2022-06-06 09:22
For those who know how to dig deeper: here is the output from the dlsupporttool.
[DLSupportTool_Output_2022-06-05T18:20:32.408950.zip](https://github.com/DisplayLink/evdi/files/8843292/DLSupportTool_Output_2022-06-05T18.20.32.408950.zip)

**Comment by ahmedrayhan** [comment] 2022-06-27 15:26
facing the same isse with 22.04 and kernel 5.15.0-40-generic. Any workaround?

**Comment by synaptics-lspintzyk** [comment] 2024-12-23 10:45
Strange issue.
If this still reproduce, I would suggest first to install latest displaylink driver and update kernel in your distro.
Disable secure boot  in bios can also help.
Please reproduce it on latest evdi driver and updated linux kernel. 
I am meanwhile closing this issue. Please raise new issue if this still happening.

**Closed by synaptics-lspintzyk** 2024-12-23 10:45 UTC
