### ISSUE TITLE
ERROR:: usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1

### ISSUE THREAD

**Issue by MonteShaffer** [DisplayLink/evdi#124] opened 2018-02-28 12:02 UTC
Hi, I followed the instructions to install the necessary elements for DisplayLink and evdi on Debian `Linux ats 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux` which I installed on an Intel NUC `NUC6CAYH`.

I verified the UEFI SecureBoot is disabled:
```
# mokutil --sb-state
SecureBoot disabled
```

I am attaching the zip file for `DLSupportTool` and note that during `dmesg` after I got the flooding error,

```
[  305.820086] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  306.814074] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  307.820878] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  308.827549] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  309.834482] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  310.841191] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  311.847757] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1

```

I decided to unplug and plug-in the monitor (Xenarc 708TSU: https://www.xenarcdirect.com/708TSU.html with eGalax touch drivers) which loads as a "usb-storage" deviceClass and then the flooding error returns

```
[  241.005037] usb 1-1.2: New USB device found, idVendor=17e9, idProduct=0199
[  241.005044] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  241.005048] usb 1-1.2: Product: Mini USB Monitor
[  241.005052] usb 1-1.2: Manufacturer: DisplayLink
[  241.005055] usb 1-1.2: SerialNumber: 100179
[  241.013017] usb-storage 1-1.2:2.0: USB Mass Storage device detected
[  241.014100] scsi host2: usb-storage 1-1.2:2.0
[  241.098143] usb 1-1.4: new full-speed USB device number 14 using xhci_hcd
[  241.220893] usb 1-1.4: New USB device found, idVendor=0eef, idProduct=0001
[  241.220901] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  241.220905] usb 1-1.4: Product: USB TouchController
[  241.220909] usb 1-1.4: Manufacturer: eGalax Inc.
[  241.224900] input: eGalax Inc. USB TouchController as /devices/pci0000:00/0000:00:15.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:0EEF:0001.0008/input/input24
[  241.225832] input: eGalax Inc. USB TouchController as /devices/pci0000:00/0000:00:15.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:0EEF:0001.0008/input/input25
[  241.226457] hid-generic 0003:0EEF:0001.0008: input,hidraw0: USB HID v2.10 Pointer [eGalax Inc. USB TouchController] on usb-0000:00:15.0-1.4/input0
[  242.027122] scsi host2: scsi scan: INQUIRY result too short (5), using 36
[  242.027135] scsi 2:0:0:0: CD-ROM                                           PQ: 0 ANSI: 0
[  242.028527] sr 2:0:0:0: [sr0] scsi3-mmc drive: 8x/40x writer xa/form2 cdda tray
[  242.028911] sr 2:0:0:0: Attached scsi CD-ROM sr0
[  242.029191] sr 2:0:0:0: Attached scsi generic sg1 type 5
[  305.820086] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  306.814074] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  307.820878] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
```

From my perspective, it appears that their is some sort of "irq-like conflict" with usb-storage meaning DisplayLink DeviceManager_0 is not "smart" to account for previous elements.

The details of the usb device show an "unrecognized element":

```

Bus 001 Device 013: ID 17e9:0199 DisplayLink 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x17e9 DisplayLink
  idProduct          0x0199 
  bcdDevice            1.36
  iManufacturer           1 DisplayLink
  iProduct                2 Mini USB Monitor
  iSerial                 3 100179
  bNumConfigurations      2
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           32
    bNumInterfaces          1
    bConfigurationValue     2
    iConfiguration          1 DisplayLink
    bmAttributes         0xc0
      Self Powered
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      6 SCSI
      bInterfaceProtocol     80 Bulk-Only
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           66
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      ** UNRECOGNIZED:  1b 5f 01 00 19 05 00 01 03 00 04 04 01 00 03 d0 00 02 04 00 bd 1f 00 01 04 01 02
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               4
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x0a  EP 10 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      2
Device Status:     0x0000
  (Bus Powered)
```

Given the "partial black box" associated with DisplayLink, I don't know if `usbfs` is an error at the evdi level or the DisplayLink level, but it appears to be a collision similar to IRQ conflicts.   

I have UEFI (unsecured) running on the Intel system, and maybe "interface 0" is the EFI partition.

```
fdisk -l
Disk /dev/sda: 111.8 GiB, 120034123776 bytes, 234441648 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 6895FA57-00ED-4EEA-90E3-F083259BFE0E

Device         Start       End   Sectors   Size Type
/dev/sda1       2048   1050623   1048576   512M EFI System
/dev/sda2    1050624 217974783 216924160 103.4G Linux filesystem
/dev/sda3  217974784 234440703  16465920   7.9G Linux swap
```

Defining the device as "bInterfaceClass         8 Mass Storage" seems odd to me and is possibly linked to the  "claimed by usb-storage" component of the error.

In the end, the software is installed, appears to run as expected, but because of this flooding message

```
[  359.142245] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  360.148960] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  361.155164] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  362.162084] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
[  363.168435] usb 1-1.2: usbfs: interface 0 claimed by usb-storage while 'DeviceManager_0' sets config #1
```
it doesn't seem to work.

As a result, I believe the `xrandr` never sees the new device as a monitor.

Thoughts?

[ats_2018-02-28T06%3A33%3A46.461726.zip](https://github.com/DisplayLink/evdi/files/1766919/ats_2018-02-28T06.3A33.3A46.461726.zip)

monte

{x:

**Comment by displaylink-dkurek** [comment] 2020-09-11 11:49
Nothing happened in this thread for quite some time. I will close it. If the issue is still visible please raise a new one with updated components and description. Thanks!

**Closed by displaylink-dkurek** 2020-09-11 11:49 UTC
