### ISSUE TITLE
kernel drm:drm_wait_vblank *ERROR* Unsupported type value 0x15b, supported mask 0x7400003f

### ISSUE THREAD

**Issue by adeptg** [DisplayLink/evdi#52] opened 2016-10-28 19:44 UTC
Hello
Dell XPS13 9360, Dell MKS14 USB3 docking station, last version of driver(1.2.65), Ubuntu 16.04 (Unity, kernel 4.4.0-45-generic). All works but a lot of errors in syslog

Oct 28 12:43:47 adept-XPS-13-9360 kernel: [ 3530.667627] [drm:drm_wait_vblank [drm]] _ERROR_ Unsupported type value 0x15b, supported mask 0x7400003f
Oct 28 12:43:47 adept-XPS-13-9360 kernel: [ 3530.672453] [drm:drm_wait_vblank [drm]] _ERROR_ Unsupported type value 0x15b, supported mask 0x7400003f

**Comment by adeptg** [comment] 2016-10-28 19:55
Looks like here is the same issue
http://displaylink.org/forum/showthread.php?t=64523

**Comment by displaylink-mlukaszek** [comment] 2016-11-17 07:50
The workaround can be found in the linked thread as well. Closing as I don't think we can do anything in evdi to improve this.

**Closed by displaylink-mlukaszek** 2016-11-17 07:50 UTC

**Comment by adeptg** [comment] 2016-11-17 19:21
Can you please advise where to ask If it's not evdi bug? Xorg? Kernel?
Thanks

**Comment by MajorTal** [comment] 2017-09-18 10:30
I upgraded the intel graphics:
https://01.org/linuxgraphics/downloads/intel-graphics-update-tool-linux-os-v2.0.5
Then moved to x-swat:
sudo add-apt-repository ppa:ubuntu-x-swat/updates
sudo apt update && sudo apt dist-upgrade
Reboot - and no more kern spam.

**Comment by stevedonato** [comment] 2019-12-28 23:54
I get this same error on linux mint 18.2 with MDM installed? Dell m6800 32mg ram ssd. Does anybody kow what the CAUSE is?
