### ISSUE TITLE
amdgpu and displaylink provide sad results

### ISSUE THREAD

**Issue by mfs12** [DisplayLink/evdi#271] opened 2021-03-24 08:39 UTC
Hey,

can you provide some idea when and if at you plan to fix your software to provide proper support amd-based linux systems?

I think there are quite some users out there sitting on their amd machines neither able to use displaylink-based docking stations nor  multiple monitors.

What do you think about that?

BR

**Comment by displaylink-emajewsk** [comment] 2021-03-24 09:02
Sad results indeed. We are very aware of the issues om amd. Unfortunately, we're spread mighty thin at the moment. I don't think we'll be able to fix it in the near future.

May I ask what distro are you using?

**Comment by mfs12** [comment] 2021-03-24 09:11
> Sad results indeed. We are very aware of the issues om amd. Unfortunately, we're spread mighty thin at the moment. I don't think we'll be able to fix it in the near future.

Sorry, to hear that for you and us.

> 
> May I ask what distro are you using?
I am using Arch Linux.

**Comment by displaylink-emajewsk** [comment] 2021-03-24 10:32
Ah, I wish we maintained an AUR ourselves. 😣

I'll try to press the amd issue internally after we're done with new kernel support.

**Comment by mfs12** [comment] 2021-03-24 12:40
> Ah, I wish we maintained an AUR ourselves.

You could ask the maintainer to hand it over too guys. :)

> 
> I'll try to press the amd issue internally after we're done with new kernel support.

thanks and good luck... :+1:

**Comment by SEGELBERT** [comment] 2021-04-08 09:37
Hey,

i'd like to push this topic. The AMD performance is really sad.
Clean Ubuntu 20.04 with Gnome and Up-To-Date Displaylink driver causes 50-90% CPU usage in idel.

My Notebook with USB Hub and 2 Displays is unusable... :(

best regards

**Comment by sickcodes** [comment] 2021-04-10 10:24
> Hey,
> 
> i'd like to push this topic. The AMD performance is really sad.
> Clean Ubuntu 20.04 with Gnome and Up-To-Date Displaylink driver causes 50-90% CPU usage in idel.
> 
> My Notebook with USB Hub and 2 Displays is unusable... :(
> 
> best regards

Try a lower resolution, that's pretty much the only solution, or a master CPU, or I think Wayland runs DL using the GPU, don't quote me though

**Comment by spikerguy** [comment] 2021-04-10 14:45
> think Wayland runs DL using the GPU, don't quote me though

If this is true then I am moving to Wayland right now :D

Even I am facing issue with AMDGPU it worked fine on 19" screen until Kde Plasma would lock up while on 24" screen it would lock up instantly. Displaying `htop` the whole columns are mixed up.
My laptop is powerful enough to handle the displaylink though still need to dig into the error logs.

```
System:    Kernel: 5.11.10-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 
           Desktop: KDE Plasma 5.21.3 Distro: Manjaro Linux base: Arch Linux 
Machine:   Type: Laptop System: TUXEDO product: TUXEDO Pulse 14 Gen1 v: Standard 
           serial: <filter> 
           Mobo: TUXEDO s model: PULSE1401 v: Standard serial: <filter> 
           UEFI: American Megatrends v: N.1.06.A01 date: 10/13/2020 
Battery:   ID-1: BAT0 charge: 46.3 Wh (99.1%) condition: 46.7/46.7 Wh (100.0%) volts: 13.0 
           min: 11.4 model: standard status: Charging 
CPU:       Info: 8-Core model: AMD Ryzen 7 4800H with Radeon Graphics bits: 64 type: MT MCP 
           arch: Zen 2 rev: 1 cache: L2: 4 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 92657 
           Speed: 1271 MHz min/max: 1700/2900 MHz boost: enabled Core speeds (MHz): 1: 1271 
           2: 1397 3: 1514 4: 1230 5: 1578 6: 1243 7: 1370 8: 1314 9: 1518 10: 1396 11: 1396 
           12: 1673 13: 1396 14: 1397 15: 1478 16: 1396 
Graphics:  Device-1: AMD Renoir vendor: Tongfang Hongkong Limited driver: amdgpu v: kernel 
           bus-ID: 04:00.0 
           Device-2: Chicony HD Webcam type: USB driver: uvcvideo bus-ID: 1-3:3 
           Display: x11 server: X.Org 1.20.10 driver: loaded: amdgpu,ati unloaded: modesetting 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD RENOIR (DRM 3.40.0 5.11.10-1-MANJARO LLVM 11.1.0) 
```

Using `DisplayLink HP Elite USB-C Docking Station` with `DL-3900` chip. 

This is my laptop currently running 5.11 as I don't want it to keep crashing on me so until then I might have to just use the native HDMI output.

**Comment by mfs12** [comment] 2021-04-16 11:17
Hey @displaylink-emajewsk , do you have any news for us poor amd users?

**Comment by spikerguy** [comment] 2021-04-17 12:11
New Update:
The system crash was RTL8153 autosuspend not supported in the kernel.
I blacklisted autosuspend and now dock seem to work fine.
I will now look into the DisplayLink Performance on `AMD Ryzen 7 4800H with Radeon Graphics`

**Comment by sebastiano1972** [comment] 2021-04-26 16:11
Hi,

I'd like to report that a similar issue exists with Fedora 33 + KDE Plasma.

My system is:

DisplayLink 5.4* and evdi v1.9.1 on Fedora 33 Kernel 5.11.15-200.fc33.x86_64 on Lenovo L14 Ryzen pro 4750U attached to Lenovo docking station USB C type 40AF with Display Link Chipset.

Seb

**Comment by mfs12** [comment] 2021-05-10 05:54
@displaylink-emajewsk Hey, are there any updates on your progress fixing this issues?

**Comment by TheBITLINK** [comment] 2021-05-10 13:30
#282 fixed the performance issues for me (Ryzen 3500U), though it's just a workaround for now.

**Comment by bnavigator** [comment] 2021-05-10 13:48
There is a Manjaro user reporting that installing "Tuxedo Control Center" and some special settings helped with the performance issue: https://aur.archlinux.org/packages/displaylink#comment-806404

**Comment by bnavigator** [comment] 2021-05-11 11:33
> The user did not share which hardware he is using it on, Definitely not AMD.

"despite amdgpu"

**Comment by MavropaliasG** [comment] 2021-05-24 03:56
Here's my [system information](https://gist.github.com/MavropaliasG/3e8b84b39d324cb7a5b8f155ed3ac7d8). The performance is really bad, just by moving the mouse slowly in that screen uses ~15% of my CPU. Playing video is out of the question. Anything slightly moving, even a progress bar, lags my system a lot. Are there any plans to improve performance? It's basically unusable in its current state, only if you want a static page to show.

**Comment by gdbd** [comment] 2021-05-27 08:57
Anyone experiencing performance issues have a look at https://github.com/DisplayLink/evdi/pull/282#issuecomment-843626578
This fix fixes the problem on X11 and I hopefully should be merged to master

**Comment by mfs12** [comment] 2021-06-01 07:05
@gdbd according to https://github.com/DisplayLink/evdi/issues/248#issuecomment-851665544 this is not right.

**Comment by mfs12** [comment] 2021-06-01 07:07
> I'll try to press the amd issue internally after we're done with new kernel support.

@displaylink-emajewsk hey, did this problem make it meanwhile to your agenda?

**Comment by opi99** [comment] 2021-06-15 07:34
Any progress on this issue?
With one monitor I get lags but with 2 monitors on the displaylink the system is unuseable.

**Comment by mfs12** [comment] 2021-07-12 08:15
Did this topic reach your work pipeline?

**Comment by mfs12** [comment] 2021-07-12 08:18
Are there any recommendation to use amd ryzen with displaylink to fix the bad performance?

**Comment by TheBITLINK** [comment] 2021-07-13 00:08
> Are there any recommendation to use amd ryzen with displaylink to fix the bad performance? Reading other issues here all people complain and there's no "real" work around? How is the current situation with wayland or xorg?

@mfs12 check my comment in #293

**Comment by mfs12** [comment] 2021-07-13 05:17
@TheBITLINK thanks for your hint, unfortunately i am using i3wm and not gnome. And running experimental patches on work laptop is not really an option right now.

**Comment by nikitagrygoriev** [comment] 2021-07-27 20:42
> @mfs12 check my comment in #293
Just in case anyone stumbles upon this issue looking for help. 
Specs:
- Fedora 34
- Wayland
- Gnome
- Xiaomi Mi Laptop Pro 15 AMD
Fix no. 1 did not help. The stutter remains even after reboot. Overall performance is tragic on external monitors, while laptop screen works fine.
Did not try fix no. 2, since I also use this laptop for work and that method sounds way too risky.
Possibly, the best option for anyone wanting to use 4k and up monitors with AMD laptops is to wait for an eventual fix or buy a laptop with Intel/NVIDIA GPU.

**Comment by irvis007** [comment] 2021-07-29 07:08
I have never, ever thought I will (ever!) write it. Ever in my life :disappointed: 
but considering how long this issue is around, 
plus looks like it is not top priority, for dLink, 
plus if you do not want risk with fix no. 2, 
and on the end you or your company is not willing to buy new laptop, with Intel/NVIDIA GPU,
Ashamedly alternative workaround: go Windows for some time, create some ~70-80GB partition and install temporary other family  operating sys :scream: 

I am desperate, I am using, docking station and kvm usb switch to easily switch set up (keyboard, mouse, monitors) between two laptops one private and second company one. I will not switch cables two times a day! first of all: it is annoying, second: unnecessary hardware degradation. 

I have tried on private laptop two solutions, helped a bit, it is usable. On company one with AMD, not too much. 
So what has left?

**Comment by spikerguy** [comment] 2021-08-27 23:42
So should we just think that the displaylink device on my desk is just a usb hub without any display controller for linux?  

Any update on this issue?

**Comment by groovyman** [comment] 2021-08-28 06:29
From the customers view the displaylink driver is a piece of sh...t, also the Windows-10 driver has a couple of problems. Displaylink should better change their website, where they still promising Linux(ubuntu) driver. Displaylink could be understood as a scamware producer ...

From the manufactor side the competition against intel/apple's thunderbold technology seems to be a lost war. Thunderbold has a better throughput over a serial bus. Besides intel shows, what went wrong with Displaylink: intel worries about a good linux integration but Displaylank did not. 
So it does not surprise me, that the Displaylink driver stopped working when the Linux developer start migrating from X11 to Wayland because Displaylink seems not to spend any money for a linux developer, who worried about a good integration into linux.

Besides, when Displaylank offered a simple support on Linux, the developer was not experienced enough in Linux  development. I did not understood, why any version of the driver was eating CPU time, while the Windows driver had less ressource consumption. There is no reason for CPU eating driver code, communication over any line should use dma, so there should be only little cpu load at all. So my understanding is, that the driver for linux was never good, anytime.

The compilation issue is another problem, that has to do with some code changes in the kernel. That can be fixed, actually the maintainer from evdi and displaylin(-rpm) fixed it. Anyway, the design of the linux driver seems to have a crappy design. Comparing the runtime behaviour with Windows shows, that there is something wrong. 
With a similar solution like the NdisWrapper for WLAN driver could be an intermediate solution for Displaylank. 

I switched from Linux to Windows10 and i hate that situation at all. I want my KDE Desktop back again. Anyway i had to recognize, that the Display-Link offer good results and a very low CPU rate. Anyway, the driver has also bugs, but it offers a very good usability with 3 4K screens on a USB 3.1gen2 with 10Hb/s.

So please @displaylink-emajewsk , wake up and find a solution. Simply accept, that the linux driver is broken by design. I do not need thunderbold with 40Gb, the 10Gb is also working perfect  for me and others. A good linux driver may be a solution for future products for embedded systems. Open your drivers and give better documentation.

**Comment by MikP0** [comment] 2021-11-16 09:16
Having the exact same Issue here. CPU: `AMD Ryzen 7 5800HS`. Is that being looked at?

**Comment by groovyman** [comment] 2021-11-17 22:28
I will try another solution, to use any notebook (regardless of its CPU) with a more simplier solution.
If you own a notebook with a USB 3.x Gen y  you may run at least 5Gbit or more over that connection.
So the idea is to (cross-) connect it with a simple minipc over a crossbar USB3 cable and to establish a fast
IP4 connection.

The idea is to run the mini-pc with a mini-linux, that is connected over a lan and by USB with the notebook.
With my USB 3.2 Gen2 i could data 10 times faster, so first try was so connect a PC with 3 4K screen and 
connect it via FreeRDP with my Windows-notebook.
`xfreerdp /multimon   /u:<user> /d:<domainname> /v:<notebook up> /gfx-thin-client /gfx-progressive /gfx:rfx`

So this was a successful lowermark test, that showed, that i can run a remote RDP over 3 4K displays. The performance was similar these monitors, that are connected to my expensive docking station with one exception: the fullsize 4k Youtube video was bad and the IP load was extreme.
But anyway, my USB-connectivity is 10 times faster ;-)

Now, where is the hardware, that could play the role of a docking station, what about:
- rasperry pi4
- or lean Asrock 4X4 BOX-R1000M with 8GB Ram and a small disk

The price could be the same as you would pay it for a powerful docking-station. But the software would be more robust that this pice of joke, that is done by display-sleepy-link on linux.

**Comment by TheBITLINK** [comment] 2021-11-18 13:01
> The price could be the same as you would pay it for a powerful docking-station. But the software would be more robust that this pice of joke, that is done by display-sleepy-link on linux.

Thing is, there is no reliable way of creating a virtual display on amdgpu on Linux, maybe at compositor level it could be done, but not at driver level, which is what DisplayLink/evdi is doing.

You could create an RDP server or really just about any remote framebuffer protocol for that matter, but the difficulty lies on creating a virtual display that you can seamlessly attach to your existing environment just as if it was another monitor. You could create headless servers that do rendering off-screen, yes, but you wouldn't be able to easily move your programs or cursor between screen since they would be basically 2 separate environments. Either that, or cloning the main screen which would lose the whole purpose of having 2 screens in most cases.

The issue isn't really on DisplayLink's side either, it's the amdgpu driver that has issues with DMA on Linux with integrated GPUs. This issue affects not only DisplayLink, but really any other piece of software that wants to access the iGPU using DMA.

There are other projects that try to do exactly what you described (display over USB to a Raspberry Pi or other computer), for example https://github.com/notro/gud 

But they have the same issues as evdi: slow copy from the GPU to the CPU, since they use the same method for accessing the GPU. Which is not really wrong, again it *should* work, and it does work with other GPU drivers, but not AMD. This bug has been an issue for a while now, and there are a few reports related to it on the mesa project, but so far nobody has looked into it.

*Maybe* there'll be more incentive on both DisplayLink's and AMD's side for fixing this once the steam deck (which also has an AMD APU) goes out, but I wouldn't really get my hopes up.

Ironically, this bug doesn't occur on AMD Chromebooks, and Chrome OS uses the exact same version of evdi that's in this repo, so they either fixed it at kernel level but didn't bother to upstream it, are using an older version of amdgpu that probably doesn't have this issue (the dmesg logs make it look like it's related to the peer to peer DMA-BUF feature introduced in Linux 5.2), or aren't using the kernel at all and doing everything at the compositor level.

Which by the way, there *are* ways to bypass DMA and let the compositor do the framebuffer copy. It takes a bit of CPU time and needs to be implemented by the compositor (so far I think only mutter allows it). That's exactly what the `disable_texture_import=1` option does, it disables the buggy zero-copy DMA so the compositor can try a fallback method. If you have that option enabled and your compositor supports it, it will run at 60fps without an issue.

Even though the amdgpu driver is the main culprit here, I think it's also wrong on DisplayLink's side to not open-source the userspace DisplayLink manager, or at least the protocol used to communicate with the docks. The only thing that evdi does is create virtual screens and copy their framebuffers to whichever userspace programs need them. DisplayLink Manager is what actually communicates with the USB docks, it grabs the frames from evdi and sends them to the dock using their proprietary protocol. If we at least had the protocol specs, we wouldn't depend on evdi for getting the frames and might have found alternative ways to send frames directly to the device a long time ago, maybe even using mesa/DRM directly, like the `udl` driver does with older DisplayLink devices (not the new ones).

**Comment by agd5f** [comment] 2021-11-29 21:32
The issue is that you are trying to read from uncached memory with the CPU so reads will always be slow.  On dGPUs the buffer is in VRAM which is an uncached PCI BAR mapping.  On APUs, if the buffer is in carve out which is uncached CPU memory.  The CPU read will only be fast if the buffer has a cached CPU mapping.  Presumably this is what Intel integrated GPU hardware provides, so that's why it is faster.   The reason https://github.com/DisplayLink/evdi/pull/282 helps is because it creates a cached CPU mapping of the memory.  However, that is not safe because you don't have any cache coherency between the CPU or the GPU in this case.  If you use the cached CPU mapping, you may end up getting stale data because the GPU is not set up to snoop the CPU's cache in this case.  

Ideally you'd do the copy with DMA rather than the CPU (E.g., the displaylink driver provides a buffer that the GPU driver can DMA to or vice versa).  If you absolutely need to use the CPU, you should use dma-buf to properly export the buffer from the GPU side and import it on displaylink side.  That will cause the buffer to be migrated to cacheable system memory.  This is how buffers are shared on hybrid graphics laptops (e.g., Intel + AMD or AMD + AMD).  Displaylink devices are not fundamentally different.

**Comment by mfs12** [comment] 2022-01-23 20:46
how are things progressing? was any of the issues fixed? how is the generic xorg and wayland support meanwhile? is it worth to give it another try?

**Comment by groovyman** [comment] 2022-01-23 23:46
Well, the AMD ThinkPad T14s supports for a Alt-DP port. So better forget solution for old notebooks (using DisplayLink) and get a cheaper and more performant connectivity using Alt-DP. There is nothing wrong using DisplayLink for old notebooks, but if your notebook has a Alt-DP, forget DisplayLink.

**Comment by mfs12** [comment] 2022-01-24 08:10
What is Alt-DP?

**Comment by groovyman** [comment] 2022-01-24 08:51
Some USB-C 3.2 connectors provides for a extension that is called DisplayPort Alternate Mode, that means, that your nodebook uses some lines to transfer a DisplayPort signal over the USB-C socket, side by side to the USB port.

see https://www.startech.com/en-us/blog/tech-talk-using-usb-c-and-displayport-over-alt

So for the newer notebooks (than come with USB-C alt dp support 1.2 and higher), there is no need to pack and transfer region of video-ram over the USB-C device, because you can use the DisplayPort signal, that can be used to transfer a digital video signal to multiple monitors over one cable.

For those notebooks let the AltDP controller do the job instead of wasting CPU time. So before you start: clarify which hardware controlling the USB-C dp line. I own a ThinkBook P16  with a AMD/Radeon & Nvidia configuration, where the ALT-C DP is controlled by the nvidia chip. In this case you have to use the proprietary Nvidia driver, because the open source Nouveau driver does not play with the Alt-DP for now. Also the Nvidia driver has some pitfalls, so there is some work to do.

But is even better that waiting in the wings for a solution for AMD cpus, that may not come (as a understood as AMD engeneer).

**Comment by mfs12** [comment] 2022-02-16 11:55
@groovyman thanks for the advice. I will test it as i found out my ryzen 4650u provides "DisplayPort alternate mode".

**Comment by groovyman** [comment] 2022-03-10 21:55
I would expect that a Ryzen 5700U would be part of a modern notebook, that comes with a USB-C AltDP socket, allowing you to connect an external display without any overcome transfer over a slow USB-3.x port. 
DisplayLink was a nice solution of old notebooks, but i assume, that you have own newer one.

**Comment by spikerguy** [comment] 2022-05-09 08:59
Sadly no permanent solution was found and I have not used the dock for the core purpose of it which was display output.

Finally deciding to sell it off as I can buy a simple usb-c dock while just using the hdmi out of the laptop itself for 1/3 of the price paid for displaylink dock.

**Comment by mfs12** [comment] 2022-05-10 06:55
Hey @spikerguy, according to @groovyman you can use DisplayPort Alternate Mode.

> Some USB-C 3.1/2 connectors provides for a extension that is called DisplayPort Alternate Mode, that means, that your notebook uses some lines of the USB-C connection to transfer a DisplayPort signal side by side to the USB port.

**Comment by groovyman** [comment] 2022-05-10 09:21
> Hey @spikerguy, according to @groovyman you can use DisplayPort Alternate Mode.
> 
> > Some USB-C 3.1/2 connectors provides for a extension that is called DisplayPort Alternate Mode, that means, that your notebook uses some lines of the USB-C connection to transfer a DisplayPort signal side by side to the USB port.

You may find these connector mostly on AMD driven notebook, because the manufacteurs do not spent additional hardware for a USB4 connectivity. The Alt-DP signal is submitted over non USB lines and this is the best way to connect your notebook with external monitors, because you can use USB3.2 to connect your notebook with other devices.

DisplayLink is a bitter non working solution for most AMD users, because some of these notebooks use a Nvidia-Chip, that controls the video-ram. As far as i understand the DisplayLink technology is, that the driver has to dig into the nvidia-chip to access the videoram and the copy it via USB to the external docking station.
So it is a better solution to install the nvidia driver, that is capable to deliver a Alt-DP signal  over the USB3.2 sockets, that cost no CPU time at all.

**Comment by lapsio** [comment] 2022-07-24 14:29
Has this been fixed? I see that https://github.com/DisplayLink/evdi/pull/351#issuecomment-1145503060 mentions it should work properly now? Could someone confirm that?

**Comment by jakub-prussak-synaptics** [comment] 2024-02-20 09:16
I will close the issue for the time being, let us know if the problems are still appearing.

**Closed by jakub-prussak-synaptics** 2024-02-20 09:16 UTC
