### ISSUE TITLE
drm-kmp-default issue

### ISSUE THREAD

**Issue by jessecooper** [DisplayLink/evdi#111] opened 2017-12-19 19:37 UTC
This package causes the following error:

**Modprobe Message:**
modprobe: ERROR: could not insert 'evdi': Invalid argument

**System Logs**
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_framebuffer_cleanup
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_framebuffer_cleanup (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_kms_helper_poll_fini
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_kms_helper_poll_fini (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_mode_vrefresh
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_mode_vrefresh (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_fb_helper_single_add_all_connectors
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_fb_helper_single_add_all_connectors (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_fb_helper_init
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_fb_helper_init (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_mode_object_find
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_mode_object_find (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_connector_register
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_connector_register (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_gem_get_pages
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_gem_get_pages (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_kms_helper_poll_init
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_kms_helper_poll_init (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_ut_debug_printk (err 0)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_framebuffer_init
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_framebuffer_init (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_framebuffer_init
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_framebuffer_init (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_framebuffer_init (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_helper_disable_unused_functions
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_helper_disable_unused_functions (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_modeset_unlock_all
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_modeset_unlock_all (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_modeset_lock_all
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_modeset_lock_all (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_fb_helper_fini
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_fb_helper_fini (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_helper_hpd_irq_event
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_helper_hpd_irq_event (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_mode_config_init
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_mode_config_init (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_crtc_cleanup
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_crtc_cleanup (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_mode_create_dirty_info_property (err 0)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_gem_create_mmap_offset
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_gem_create_mmap_offset (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_dev_set_unique (err 0)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_encoder_cleanup
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_encoder_cleanup (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_gem_object_init
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_gem_object_init (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_connector_unregister
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_connector_unregister (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_gem_prime_handle_to_fd
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_gem_prime_handle_to_fd (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_crtc_init
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_crtc_init (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_gem_object_lookup
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_gem_object_lookup (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_framebuffer_unregister_private
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_framebuffer_unregister_private (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_gem_prime_fd_to_handle
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_gem_prime_fd_to_handle (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_mode_connector_update_edid_property
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_mode_connector_update_edid_property (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_fb_helper_prepare
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: Unknown symbol drm_fb_helper_prepare (err -22)
Dec 19 11:24:02 linux-olhs.suse kernel: evdi: disagrees about version of symbol drm_connector_init

Module works correctly after this package is removed

**OS:** Opensuse Leap 42.3
**Kernel:** 4.4.103-36-default

**Comment by xmentos** [comment] 2018-01-08 10:33
Same problem here on openSUSE Leap 42.3 with kernel 4.4.104. The problem is that the Intel i915 driver symbols (in my case) got overwritten by the module symbols from the 'drm-kmp-default' package. Uninstallation and reboot fixed the problem for me.

**Comment by displaylink-dkurek** [comment] 2020-09-11 11:49
Nothing happened in this thread for quite some time. I will close it. If the issue is still visible please raise a new one with updated components and description. Thanks!

**Closed by displaylink-dkurek** 2020-09-11 11:49 UTC
