### ISSUE TITLE
Ubuntu 16.10 running slow

### ISSUE THREAD

**Issue by ashic** [DisplayLink/evdi#51] opened 2016-10-28 00:49 UTC
Seems this is happening to a few of us: 

http://www.displaylink.org/forum/showthread.php?p=81728&posted=1#post81728 

I have a Precision 5510, and connected it to a Dell monitor with both a Dell USB 3 dongle, and a Dell D3100 dock (which is "linux compatible". Even with the latest Displaylink drivers, I'm seeing terrible performance on the second monitor. However, if I connect the monitor directly to the laptop's HDMI port, everything runs fine. I've noticed the following:
1. Using bumblebee, running glxspheres on second monitor using Displaylink I get 1 fps when on intel graphics (both with Displayport, and HDMI connected to dock). 
2. Using bumblebee optirun, I get 200fps. 
3. Using bumblebee on the laptop monitor, I get 60 fps when on intel grpahics.
4. Using bumblebee on the laptop monitor, I get 200 fps when using optirun.
5. If I switch to Prime graphics using the dock, I get 2000 fps on the second monitor, but the internal monitor shuts off.

I've also run it using the open source drivers, and I get 60fps on the internal screen, but only 1 fps on the external one. Optirun doesn't work with the open source driver.

I'm currently running it with a seperate HDMI cable, which gives ok performance, but means the expensive D3100 dock is essentially a USB + ethernet hub; functionality which can be got from a £15 component. The same laptop runs when connected to an external 4K monitor using a Plugable thunderbolt 3 adapter, so I have to come to the conclusion that Displaylink just doesn't work.

**Comment by displaylink-mlukaszek** [comment] 2016-11-04 23:01
Bumblebee is definitely not a supported configuration, as evdi needs reverse PRIME to work. This leaves you with nouveau which should work, and seeing 1 fps is not right. This is a very powerful machine, so I wonder how well nouveau supports this GPU (NVIDIA Quadro M1000M). Is the same terrible performance reproducible with monitorsim from [this project](https://github.com/mlukaszek/evdipp)? This would rule out DisplayLink-specific code and hardware.

**Comment by tomdee** [comment] 2016-12-09 22:47
I see this problem too on Arch Linux. dragging glxgears to the external monitor - 1fps, laptop screen gives me 60fps

**Comment by jkldgoefgkljefogeg** [comment] 2017-01-15 18:54
I also have this issue with Intel HD Graphics 4000 on Ubuntu 16.10. Displaylink screen runs at 1fps, cursor flashes. It was working fine on Ubuntu 16.04

**Comment by gnuyork** [comment] 2017-01-22 21:08
Got the same issue with Gentoo Linux, 4.9.5 kernel, 1.2.65 kernel.

**Comment by Exel232** [comment] 2017-02-09 16:36
I also have this issue on Archlinux on 4.9.8 kernel and udl driver for a USB2 device. This seems not to be an issue of the evdi module, but rather a problem with OpenGL rendering.
I get normal fps on my external displaylink monitors by starting applications with vglrun. Please test if this also applies to your configurations.

**Comment by displaylink-mlukaszek** [comment] 2017-02-17 08:24
We've spent some time analysing the root cause, and it looks like X problem:
https://bugs.freedesktop.org/show_bug.cgi?id=99547

Note that if any part of the window stays on the built-in screen, the rendering on DisplayLink screen would not be 1 fps.

**Comment by vladrulez** [comment] 2017-03-31 10:24
I have Dell XPS 15 9550 notebook with Intel HD Graphics 530 and NVIDIA GeForce GTX 960M. I have the same problem with 1 FPS on Intel video, but when I switch to Nvidia all works fine.
The problem showed itself after upgrade to Ubuntu 16.10.

**Comment by matchilling** [comment] 2017-06-10 10:18
Can confirm same behaviour on my Dell XPS 13 9360 running on 16.04. Annoyingly enough Dell didn't add a standard display port to that model so that the only way to connect an external screen is through the displaylink :angry:

**Comment by kq01526** [comment] 2017-06-14 00:07
> @matchilling wrote:
> Annoyingly enough Dell didn't add a standard display port to that model so that the only way to connect an external screen is through the displaylink :angry:

Wrong. Apparently it has a Thunderbolt 3 port, which could be used to connect a external display:

https://en.wikipedia.org/wiki/Dell_XPS#XPS_13_Touch_.289333.2F9343.2F9350.2F9360.2F9365.29

**Comment by kq01526** [comment] 2017-06-14 00:14
http://displaylink.org/forum/showthread.php?t=65240

**Comment by rewtd** [comment] 2017-06-29 16:04
The problem appears to be _VSync_ on Intel. This fixed the issue on 16.04.2 for me.
```
Section "Device"
    Identifier  "Intel"
    Driver      "intel"
    Option      "VSync" "false"
EndSection
```

**Comment by vladrulez** [comment] 2017-06-30 14:03
@rewtd 
Thank you.
I have fixed my second monitor problem on Intel video. Just created this file:
$ cat /usr/share/X11/xorg.conf.d/10-intel.conf 
Section "Device"
    Identifier  "Intel"
    Driver      "intel"
    Option      "VSync" "false"
EndSection

**Comment by cherepanov** [comment] 2017-06-30 17:55
I ended up with this configuration
$ cat /etc/X11/xorg.conf.d/20-intel.conf 
Section "Device"
  Identifier "Intel Graphics"
  Driver "Intel"
  Option "AccelMethod" "sna"
  Option "TearFree" "true"
  Option "TripleBuffer" "true"
  Option "MigrationHeuristic" "greedy"
  Option "Tiling" "true"
  Option "Pageflip" "true"
  Option "ExaNoComposite" "false"
  Option "Tiling" "true"
  Option "Pageflip" "true"
  Option "VSync" "false"
EndSection

**Comment by sandra1n** [comment] 2017-07-13 08:58
@cherepanov Hey, Thanks. Your solution is more fast than others

**Comment by dragon788** [comment] 2017-08-16 15:54
You can use the following code by copy and pasting or easily script the creation of this file (eg for imaging/preseed where it can saved into a script and then non-interactively used by either defining NOPASSWD for sudo for the setup user against the script or just running the commands as root during the preseed).
```
sudo mkdir -p /etc/X11/xorg.conf.d/
sudo tee /etc/X11/xorg.conf.d/20-intel.conf <<EOF
Section "Device"
  Identifier "Intel Graphics"
  Driver "Intel"
  Option "AccelMethod" "sna"
  Option "TearFree" "true"
  Option "TripleBuffer" "true"
  Option "MigrationHeuristic" "greedy"
  Option "Tiling" "true"
  Option "Pageflip" "true"
  Option "ExaNoComposite" "false"
  Option "Tiling" "true"
  Option "Pageflip" "true"
  Option "VSync" "false"
EndSection
EOF
```

**Comment by t2javiers** [comment] 2017-09-01 01:24
No luck here. Still painfully slow running a two monitor setup. Any other suggestions or work around out there?

**Comment by dragon788** [comment] 2017-09-14 20:40
@t2javiers what is your host machine's hardware specs? You probably want a decently fast CPU with a good amount of RAM if you are doing 1080p or larger external monitors.

**Comment by sandra1n** [comment] 2017-09-15 11:44
@dragon788 may I say somth. 16 ram, i7, I don't know why but Ubuntu has some properties on Intel HD integrated graphics that  extremely slows picture on external monitor as say topic starter. anyway with config update what described in previous messages  situation may change on first look. but after short time of use - I was surprised Google Chrome blinking and a lot of problems with GPu accelerations problems I was supposed refuse to use 3100

**Comment by t2javiers** [comment] 2017-09-25 20:44
@dragon788 I am on i7 3rd gen with 8gb of ram. Displayport drivers working perfectly fine on Windows 10 (same machine) and Macbook Air 2015. I do believe there is still something awry with the DisplayPort drivers or how the GPU is being handled.

**Comment by dragon788** [comment] 2017-09-27 19:03
I haven't been able to play with this to the point of getting the driver working (was dabbling in my free time at work), but I will try to give it a shot soon. Is everybody using 16.04 LTS or 16.10 or have some moved on to 17.04?

I wouldn't be surprised if some still using 16.04 have been hit with this as the Xorg server there seems to be affected by some issues in the Intel/Nvidia interactions on the latest "stable" versions (though some people have better luck installing the latest Xorg from PPA).

From reading the kernel bug linked above and other issues about DisplayLink on Linux I learned that there were a couple changes to how the Intel driver and DRM/DRI/PRIME and discrete GPUs (Nvidia/AMD) play together, and there are fixes for Nouveau but they might not have hit the Nvidia drivers yet. Essentially the problem comes from the X server not telling the devices about each other so the dGPU can't talk to the iGPU and tell it to draw things for it, and this is even worse when you add a "virtual" GPU via DisplayLink that wants somebody to draw things for it to display to an external monitor.

See also the forum post with a potential workaround and let us know if that fixes it. https://github.com/DisplayLink/evdi/issues/51#issuecomment-308283584

**Comment by jandoerntlein** [comment] 2017-10-12 07:06
I am facing the same problem. As described in the thread on displaylink.org, I tried various configurations in /etc/X11/xorg.conf.d but it seems like this had no effect. For verification, it would be helpful to know:
- how can I see the currently active driver's name ("intel", "Intel", "i915", "modesetting")? I am not sure if the options in this directory are really commited to the driver.
- how can I query X11 to see if the changes really had an effect (query for "PageFlip" setting or vsync setting)?
- how can I verify that the connections runs at the correct speed (e.g. 60 FPS) from a system point of view? The only way to verify if a patch works is "by eye"... This might be distorted by the window manager's framerate.

Since all of the above patches did not work (in my opinion, since I do not have any command queries to really verify the system status), I finally added this PPA https://launchpad.net/~xorg-edgers/+archive/ubuntu/ppa and updated my system. It might "feel" a little bit better now, but still not fluent enough.

Any more suggestions are welcome.

**Comment by M-arcus** [comment] 2017-11-08 11:18
Are the permissions of the X11 folder and the conf file important?

**Comment by lkoning** [comment] 2017-11-14 07:06
using a Fujitsu Displaylink adapter here with a Fujitsu monitor. It's connected to the adapter by Displaylink. I am running a Lenovo Thinkpad E540 with the Intel driver. Electron apps (Like Franz for example) and Google Chrome are running dead slow. Also the mouse responsiveness is bad. I've tried the above suggestions for the Xorg-config. Doesn't do anything.

**Comment by jandoerntlein** [comment] 2017-11-15 12:59
For me it's a T460p. Changed to the nvidia-387 driver now (using prime-select). Scrolling in Firefox or Sublime Text is extremely slow. Is this issue independent of using intel/nvidia drivers?

**Comment by displaylink-dkurek** [comment] 2018-07-18 06:16
A lot of water has flowed under the bridge from this thread had started. I will close this issue as some workarounds have been found. If you still see an issue with fps with the latest software (evdi/kernel/xorg) please raise a new issue.

**Closed by displaylink-dkurek** 2018-07-18 06:16 UTC
