### ISSUE TITLE
evdi framebuffer problem

### ISSUE THREAD

**Issue by Prutheus** [DisplayLink/evdi#59] opened 2016-11-19 08:42 UTC
System:
archlinux
kernel 4.8.4-1

Problem:
I have a displaylink device, so I have evdi also installed.
I have a problem on my dell xps 13 9360. I have a little screen freeze every ~10 secs, on hdmi display via D3100 docking station, via usb-c-to-hdmi and on the laptop screen. Everytime it lags, I get an message in my journal what could raise this error? how could i fix it? (btw, maybe it is useful to know, that when the docking station is connected, my laptop screen is getting dark/disabled after some little time, the brightness get zero'ed)

Error in journal:
```
Nov 19 09:22:07 XPS kernel: evdi: [V] painter_unlock:165 
Nov 19 09:22:07 XPS kernel: evdi: [V] evdi_painter_grabpix_ioctl:556 
Nov 19 09:22:07 XPS kernel: evdi: [V] painter_lock:159 
Nov 19 09:22:07 XPS kernel: evdi: [V] copy_pixels:121 
Nov 19 09:22:07 XPS kernel: evdi: [V] copy_pixels:139 copy rect 0,0-1920,1080
Nov 19 09:22:07 XPS kernel: evdi: [V] painter_unlock:165 
Nov 19 09:22:07 XPS kernel: evdi: [V] painter_lock:159 
Nov 19 09:22:07 XPS kernel: evdi: [V] painter_unlock:165 
Nov 19 09:22:07 XPS kernel: evdi: [V] evdi_user_framebuffer_dirty:232 
Nov 19 09:22:07 XPS kernel: evdi: [V] evdi_handle_damage:87 
Nov 19 09:22:07 XPS kernel: evdi: [V] painter_lock:159 
Nov 19 09:22:07 XPS kernel: evdi: [V] painter_unlock:165 
Nov 19 09:22:07 XPS kernel: evdi: [V] painter_lock:159 
Nov 19 09:22:07 XPS kernel: evdi: [V] evdi_painter_mark_dirty:333 (dev=1) 0,0-1920,1080
```

**Comment by displaylink-mlukaszek** [comment] 2017-02-17 08:39
This looks like a duplicate of #57. Please try the new 1.3 release.

**Closed by displaylink-mlukaszek** 2017-02-17 08:39 UTC
