### ISSUE TITLE
Gnome seriosly stutters after a bit on 2x 3440x1440px monitors via a dock.

### ISSUE THREAD

**Issue by NinjaTurtle007** [DisplayLink/evdi#138] opened 2018-09-11 09:13 UTC
I'm using lenovo x1 Yoga with their proprieatary dock to connect to 2 ultrawide 3440x1440px monitors.
I'm with intel graphics 520

Since I upgraded to Ubuntu that is using Gnome, everything starts to stutter after using the DE a bit. Even typing this is appearing with a slight delay on the monitor. 

I tried the solution suggested here of creating 20-intel.conf file in /usr/share/X11/xorg.conf.d/ with the following contents:

> Section "Device"
  Identifier "Intel Graphics"
  Driver "Intel"
  Option "AccelMethod" "sna"
  Option "TearFree" "true"
  Option "TripleBuffer" "true"
  Option "MigrationHeuristic" "greedy"
  Option "Tiling" "true"
  Option "ExaNoComposite" "false"
  Option "Pageflip" "true"
EndSection

But that doesn't help. 

What else I migh try or maybe editing those settings?

Also Am I right that I don't have to install anything DisplayLink related since it comes with Ubuntu by default?

Ubuntu 18.04 Here with Gnome.

**Comment by displaylink-dkurek** [comment] 2020-09-11 11:51
Nothing happened in this thread for quite some time. I will close it. If the issue is still visible please raise a new one with updated components and description. Thanks!

**Closed by displaylink-dkurek** 2020-09-11 11:51 UTC
