### ISSUE TITLE
kernel-5.11.1 break evdi-1.7 again

### ISSUE THREAD

**Issue by jerome-diver** [DisplayLink/evdi#258] opened 2021-02-24 20:31 UTC
Archlinux
kernel:
linux-5.11.1
and linux-zen-5.11.1

there is no dkms evdi module in the tree, because last kernel update break the evdi-1.7 module to be build (any other evdi last update module doesn't want to build and then, doesn't work)

**Comment by joren485** [comment] 2021-02-25 07:43
This looks like a duplicate of #249.

**Comment by jerome-diver** [comment] 2021-02-25 17:43
yes, thank you

**Comment by dzackgarza** [comment] 2021-02-27 20:51
Also seeing this issue on Arch as of this/last week. The patch mentioned in the linked thread seems to be working for the moment:
https://github.com/DisplayLink/evdi/issues/249#issuecomment-780332761

**Comment by Morta1985** [comment] 2021-02-27 21:37
This new Patch for evdi 1.7.2 freeze Arch Linux and Cinnamon Desktop when i switch off the screen. Poweroff and reboot is during very long but its works more or less.

**Comment by dzackgarza** [comment] 2021-03-06 04:02
> This new Patch for evdi 1.7.2 freeze Arch Linux and Cinnamon Desktop when i switch off the screen. Poweroff and reboot is during very long but its works more or less.

Yep, I'm also seeing all kinds of issues after applying that patch....various wake-from-suspend and startup problems, and (maybe unrelated) somehow having certain BIOS settings reset periodically.

**Comment by timnolte** [comment] 2021-04-06 03:45
Seeing this issue on the latest Pop!_OS as well.

**Comment by toniToniDev** [comment] 2021-04-08 07:12
Yep... Pop!_OS affected and my working docking station, stopped working for the displays...

**Comment by cement-head** [comment] 2021-06-15 18:52
Fix is in master, needs to be built for Ubuntu: https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1931547

**Closed** 2021-08-05 08:36 UTC
