### ISSUE TITLE
Mainline Kernel 4.13 compile errors

### ISSUE THREAD

**Issue by AndyGee** [DisplayLink/evdi#99] opened 2017-09-04 08:17 UTC
make -C /lib/modules/4.13.0-041300-generic/build M=$PWD
make[2]: Entering directory '/usr/src/linux-headers-4.13.0-041300-generic'
  CC [M]  /home/andy/github/evdi/module/evdi_connector.o
  CC [M]  /home/andy/github/evdi/module/evdi_gem.o
/home/andy/github/evdi/module/evdi_gem.c: In function ‘evdi_gem_put_pages’:
/home/andy/github/evdi/module/evdi_gem.c:154:3: error: implicit declaration of function ‘drm_free_large’ [-Werror=implicit-function-declaration]
   drm_free_large(obj->pages);
   ^~~~~~~~~~~~~~
/home/andy/github/evdi/module/evdi_gem.c: In function ‘evdi_prime_create’:
/home/andy/github/evdi/module/evdi_gem.c:276:15: error: implicit declaration of function ‘drm_malloc_ab’ [-Werror=implicit-function-declaration]
  obj->pages = drm_malloc_ab(npages, sizeof(struct page *));
               ^~~~~~~~~~~~~
/home/andy/github/evdi/module/evdi_gem.c:276:13: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
  obj->pages = drm_malloc_ab(npages, sizeof(struct page *));

**Comment by OursDesCavernes** [comment] 2017-09-15 19:19
Hello, I tried konserw's fix and it works for me.

**Comment by laurenblackfox** [comment] 2017-10-05 08:19
I have this issue too. We use these displaylinks ubiquitously where I work, and the several of us that use Arch are stuck on 4.12, or LTS.

**Comment by DanySK** [comment] 2017-10-05 08:29
I can confirm the issue on Arch. I had to switch to LTS.

**Comment by hjaltioj** [comment] 2017-10-06 15:06
Is there anyone who knows how to install evdi/displayport on openSUSE Tumbleweed 42.3 ? :)

**Comment by tartansandal** [comment] 2017-10-07 01:48
I can get 1.5.0 to compile against the current fedora 26 kernel , but get a core dump on module load. See comment on  https://github.com/displaylink-rpm/displaylink-rpm/issues/32

**Comment by alhalama** [comment] 2017-10-11 00:34
@tartansandal  There is a comment on [the forum](http://displaylink.org/forum/showthread.php?t=65577) that evdi 1.5 is not api compatible with DisplaylinkManager 1.3.x.  I submitted [pull request 41 on the displaylink-rpm](https://github.com/displaylink-rpm/displaylink-rpm/pull/41) project that has both updated.

**Comment by tartansandal** [comment] 2017-10-11 00:42
Thanks @alhalama. I saw both of those. Hope to have a chance to check them out tonight.

**Comment by displaylink-mlukaszek** [comment] 2017-10-26 13:47
This should be already fixed by v1.5.0 evdi release and new DisplayLink driver that is now API-compatible.

**Closed by displaylink-mlukaszek** 2017-10-26 13:47 UTC
