### ISSUE TITLE
Screen continiously becoming disabled and re-enabled again because of USB issues(?)

### ISSUE THREAD

**Issue by yofWeHan4** [DisplayLink/evdi#160] opened 2019-06-02 14:49 UTC
My Lenovo enovo ThinkPad Hybride Usb C and Usb A Docking Station + lenovo Yoga c930 with Fedora 30 linux is unusable because of constant disabling of the external screen, and then a few seconds later enabling again. It seems like the USB disconnect all the time. Screen is turning black, then fast changing resolution on my laptop screen and then the external screen is turned on again. This happens every minute or so, especially when working on the external screen. It doesnt seem to happen when working on the laptop screen itself (or at least much less frequent). This is a very serious bug!

[user@computer: /home/user]$ uname -a
Linux computer.network.net 5.1.5-300.fc30.x86_64 #1 SMP Sat May 25 18:00:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

This happens in dmesg at that moment:

[ 1113.817144] retire_capture_urb: 122 callbacks suppressed
[ 1113.859900] usb 4-2.2: USB disconnect, device number 13
[ 1113.873923] evdi: [D] evdi_painter_disconnect:704 (dev=1) Disconnected from 00000000e563ab86
[ 1113.873929] evdi: [D] evdi_detect:95 (dev=-1) poll connector state: disconnected
[ 1113.873959] evdi: [D] evdi_driver_postclose:143 (dev=-1) Process tries to close us, postclose
[ 1113.873962] evdi: [I] Task 1883 (DesktopManagerE) of process 1879 (DisplayLinkMana)
[ 1113.881031] evdi: [D] evdi_detect:95 (dev=-1) poll connector state: disconnected
[ 1113.881071] evdi: [D] evdi_detect:95 (dev=-1) poll connector state: disconnected
[ 1113.895049] evdi: [D] evdi_detect:95 (dev=-1) poll connector state: disconnected
[ 1113.897608] evdi: [D] evdi_painter_dpms_notify:543 (dev=-1) Notifying dpms mode: 3
[ 1113.897610] evdi: [W] evdi_painter_send_dpms:379 Painter is not connected!
[ 1113.897756] evdi: [D] evdi_painter_dpms_notify:543 (dev=-1) Notifying dpms mode: 3
[ 1113.897758] evdi: [W] evdi_painter_send_dpms:379 Painter is not connected!
[ 1115.660921] usb 4-2.2: new SuperSpeed Gen 1 USB device number 14 using xhci_hcd
[ 1115.673316] usb 4-2.2: New USB device found, idVendor=17e9, idProduct=6015, bcdDevice=31.04
[ 1115.673318] usb 4-2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1115.673319] usb 4-2.2: Product: ThinkPad Hybrid USB-C with USB-A Dock
[ 1115.673320] usb 4-2.2: Manufacturer: DisplayLink
[ 1115.673320] usb 4-2.2: SerialNumber: 10487520
[ 1115.687137] usb 4-2.2: Warning! Unlikely big volume range (=767), cval->res is probably wrong.
[ 1115.687138] usb 4-2.2: [4] FU [Mic Capture Volume] ch = 2, val = -4592/7680/16
[ 1115.687619] usb 4-2.2: Warning! Unlikely big volume range (=672), cval->res is probably wrong.
[ 1115.687620] usb 4-2.2: [7] FU [Lenovo USB Audio Playback Volume] ch = 6, val = -10752/0/16
[ 1116.292638] evdi: [D] evdi_painter_connect:625 (dev=-1) Process is trying to connect
[ 1116.292639] evdi: [I] Task 1883 (DesktopManagerE) of process 1879 (DisplayLinkMana)
[ 1116.292641] evdi: [D] evdi_painter_connect:675 (dev=1) Connected with 000000000dbc7859
[ 1116.292643] evdi: [D] evdi_detect:91 (dev=1) poll connector state: connected
[ 1116.294022] evdi: [D] evdi_detect:91 (dev=1) poll connector state: connected
[ 1116.294023] evdi: [D] evdi_painter_get_edid_copy:230 (dev=1) EDID valid
[ 1116.294110] evdi: [D] evdi_detect:91 (dev=1) poll connector state: connected
[ 1116.294110] evdi: [D] evdi_painter_get_edid_copy:230 (dev=1) EDID valid
[ 1116.302526] evdi: [D] evdi_detect:91 (dev=1) poll connector state: connected
[ 1116.302527] evdi: [D] evdi_painter_get_edid_copy:230 (dev=1) EDID valid
[ 1117.511806] evdi: [D] evdi_painter_dpms_notify:543 (dev=1) Notifying dpms mode: 0
[ 1117.511813] evdi: [D] evdi_painter_mode_changed_notify:602 (dev=1) Notifying mode changed: 1920x1200@60; bpp 32; 
[ 1117.511814] evdi: [D] evdi_log_pixel_format:570 pixel format XR24 little-endian (0x34325258)
[ 1117.511814] evdi: [D] evdi_painter_dpms_notify:543 (dev=1) Notifying dpms mode: 0

or sometimes this:

  886.246970] retire_capture_urb: 38 callbacks suppressed
[  891.258967] retire_capture_urb: 4286 callbacks suppressed
[  891.409888] hub 4-2:1.0: hub_ext_port_status failed (err = -110)
[  894.353196] usb 4-2.2: Disable of device-initiated U1 failed.
[  894.360155] usb 4-2.2: Disable of device-initiated U2 failed.
[  894.374165] usb 4-2.2: Set SEL for device-initiated U1 failed.
[  894.381654] usb 4-2.2: Set SEL for device-initiated U2 failed.
[  894.396267] usb 4-2.2: Set SEL for device-initiated U1 failed.
[  894.403204] usb 4-2.2: Set SEL for device-initiated U2 failed.
[  894.471422] usb 4-2.2: reset SuperSpeed Gen 1 USB device number 10 using xhci_hcd
[  894.502054] usb 4-2.2: Warning! Unlikely big volume range (=767), cval->res is probably wrong.
[  894.502056] usb 4-2.2: [4] FU [Mic Capture Volume] ch = 2, val = -4592/7680/16
[  894.502491] usb 4-2.2: Warning! Unlikely big volume range (=672), cval->res is probably wrong.
[  894.502492] usb 4-2.2: [7] FU [Lenovo USB Audio Playback Volume] ch = 6, val = -10752/0/16
[  894.503673] usb 4-2.2: usbfs: process 6870 (DeviceWindowDis) did not claim interface 0 before use
[  894.565219] usb 4-2.2: Disable of device-initiated U1 failed.
[  894.576239] usb 4-2.2: Disable of device-initiated U2 failed.
[  894.591249] usb 4-2.2: Set SEL for device-initiated U1 failed.
[  894.598254] usb 4-2.2: Set SEL for device-initiated U2 failed.
[  894.598261] usb 4-2.2: 3:1: usb_set_interface failed (-71)
[  894.606232] usb 4-2.2: USB disconnect, device number 10
[  894.606701] usb 4-2.2: 3:1: usb_set_interface failed (-71)
[  894.632481] evdi: [D] evdi_painter_disconnect:704 (dev=1) Disconnected from 000000006f9a89d3
[  894.632488] evdi: [D] evdi_detect:95 (dev=-1) poll connector state: disconnected
[  894.632537] evdi: [D] evdi_driver_postclose:143 (dev=-1) Process tries to close us, postclose
[  894.632540] evdi: [I] Task 1883 (DesktopManagerE) of process 1879 (DisplayLinkMana)
[  894.635569] evdi: [D] evdi_detect:95 (dev=-1) poll connector state: disconnected
[  894.635618] evdi: [D] evdi_detect:95 (dev=-1) poll connector state: disconnected
[  894.647748] evdi: [D] evdi_detect:95 (dev=-1) poll connector state: disconnected
[  894.649919] evdi: [D] evdi_painter_dpms_notify:543 (dev=-1) Notifying dpms mode: 3
[  894.649920] evdi: [W] evdi_painter_send_dpms:379 Painter is not connected!
[  894.650049] evdi: [D] evdi_painter_dpms_notify:543 (dev=-1) Notifying dpms mode: 3
[  894.650050] evdi: [W] evdi_painter_send_dpms:379 Painter is not connected!
[  896.391713] usb 4-2.2: new SuperSpeed Gen 1 USB device number 11 using xhci_hcd
[  896.404305] usb 4-2.2: New USB device found, idVendor=17e9, idProduct=6015, bcdDevice=31.04
[  896.404306] usb 4-2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  896.404307] usb 4-2.2: Product: ThinkPad Hybrid USB-C with USB-A Dock
[  896.404308] usb 4-2.2: Manufacturer: DisplayLink
[  896.404308] usb 4-2.2: SerialNumber: 10487520
[  896.417847] usb 4-2.2: Warning! Unlikely big volume range (=767), cval->res is probably wrong.
[  896.417848] usb 4-2.2: [4] FU [Mic Capture Volume] ch = 2, val = -4592/7680/16
[  896.418292] usb 4-2.2: Warning! Unlikely big volume range (=672), cval->res is probably wrong.
[  896.418293] usb 4-2.2: [7] FU [Lenovo USB Audio Playback Volume] ch = 6, val = -10752/0/16
[  897.003241] evdi: [D] evdi_painter_connect:625 (dev=-1) Process is trying to connect
[  897.003242] evdi: [I] Task 1883 (DesktopManagerE) of process 1879 (DisplayLinkMana)
[  897.003245] evdi: [D] evdi_painter_connect:675 (dev=1) Connected with 000000002fadfc55
[  897.003247] evdi: [D] evdi_detect:91 (dev=1) poll connector state: connected
[  897.005228] evdi: [D] evdi_detect:91 (dev=1) poll connector state: connected
[  897.005230] evdi: [D] evdi_painter_get_edid_copy:230 (dev=1) EDID valid
[  897.005310] evdi: [D] evdi_detect:91 (dev=1) poll connector state: connected
[  897.005310] evdi: [D] evdi_painter_get_edid_copy:230 (dev=1) EDID valid
[  897.013259] evdi: [D] evdi_detect:91 (dev=1) poll connector state: connected
[  897.013260] evdi: [D] evdi_painter_get_edid_copy:230 (dev=1) EDID valid
[  897.289545] evdi: [D] evdi_painter_dpms_notify:543 (dev=1) Notifying dpms mode: 0
[  897.289549] evdi: [D] evdi_painter_mode_changed_notify:602 (dev=1) Notifying mode changed: 1920x1200@60; bpp 32; 
[  897.289550] evdi: [D] evdi_log_pixel_format:570 pixel format XR24 little-endian (0x34325258)
[  897.289551] evdi: [D] evdi_painter_dpms_notify:543 (dev=1) Notifying dpms mode: 0

**Comment by displaylink-dkurek** [comment] 2019-06-06 06:22
Have you tried different USB cable? Try some short one of a good quality. You can also try different USB
port in laptop. If this will not help please take a look at https://github.com/displaylink-rpm/displaylink-rpm#dell-d6000. Different dock but the problem seems similar.

**Comment by yofWeHan4** [comment] 2019-06-06 06:33
I have disabled the power saving mode for the audio device as in the post as I also found this on the internet, but same issue remains.

I have tried with another cable, but same issue. Both cables were high quality.

It does not seem like a hardware issue to me, as it is only occuring when using the external screen. If I do not have any windows drawn on the external screen; no issue occurs and the dock doesn't show the disconnects.

**Comment by peterjanes** [comment] 2020-01-02 18:35
This has started to recur for me today, even with the PulseAudio workaround. (I'm the one who added that workaround to the DisplayLink RPM doc; it was based on info I found elsewhere, and I don't actually understand the root cause.)

kernel: `5.3.16-300.fc31.x86_64` (Fedora 31)
displaylink-rpm: `displaylink-1.6.3-1.x86_64`
evdi: `1.6.3` (rebuilt today using `dkms install`)

**Comment by peterjanes** [comment] 2020-01-02 20:43
It looks like downgrading the kernel to `5.3.15-300.fc31.x86_64` has resolved this for me for now. I don't see anything obviously related in the changelog to 5.3.16, but perhaps the info will help someone else.

**Comment by Lqp1** [comment] 2020-01-03 08:59
On 4.19.86 kernel PulseAudio fix did it for me; before applying the fix I had several random disconnects, but now it's very stable. I also lowered a bit the resolution, don't know if that may be related ?

**Comment by displaylink-emajewsk** [comment] 2021-08-05 07:57
Sounds like an old kernel issue. Closing.
Please create a new issue if the problem resurfaces. Thanks!

**Closed by displaylink-emajewsk** 2021-08-05 07:57 UTC
